import {sourceData,sourceCoding} from '../scripts/read-source.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {labBuildProgram,labRequest,labParseResponse,labDiagnosticHelp,labCheckWorkedResult} from '../src/coding-core.mjs';
const catalog=sourceCoding().questions;
const q=catalog.find(q=>q.id==='b1-add'),hex=x=>Buffer.from(x).toString('hex');
test('Coding catalog has independent questions and complete metadata for all ten books',()=>{assert.equal(catalog.length,114);assert.equal(new Set(catalog.map(x=>x.courseId)).size,10);assert.equal(catalog.reduce((n,x)=>n+x.tests.length,0),553);assert.equal(new Set(catalog.map(x=>x.id)).size,114);for(const x of catalog){assert.ok(x.driver.includes('int main('));assert.ok(x.prompt&&x.signature&&x.explanation&&x.chapterTitle);assert.ok(x.tests.length>=4);assert.notEqual(x.starter,x.solution);}});
test('Run and Check use distinct supplied drivers and main.cpp line directives',()=>{const a=labBuildProgram(q.starter,q,'run');assert.ok(a.startsWith('#line 1 "main.cpp"'));assert.ok(a.includes(q.driver));assert.ok(!a.includes('@STUDY:'));const b=labBuildProgram(q.solution,q,'test','abc');assert.ok(b.includes('@STUDY:abc|'));assert.ok(b.includes('study_tests.cpp'));assert.throws(()=>labBuildProgram(q.solution,q,'test','bad\nnonce'));assert.equal(labBuildProgram('int main(){}',null),'#line 1 "main.cpp"\nint main(){}\n');});
test('Request explicitly uses a real C++20 executor and input',()=>{const r=labRequest('code','7 5\n');assert.equal(r.allowStoreCodeDebug,false);assert.equal(r.options.compilerOptions.executorRequest,true);assert.equal(r.options.filters.execute,true);assert.equal(r.options.executeParameters.stdin,'7 5\n');assert.ok(r.options.userArguments.includes('-std=c++20'));});
const payload=stdout=>({code:0,didExecute:true,stdout:stdout.map(text=>({text})),stderr:[],buildResult:{code:0,stderr:[]}});
test('Only a full set of matching completed test records passes',()=>{const lines=q.tests.map(t=>'@STUDY:abc|'+t.id+'|PASS|'+hex(t.expected)+'|'+hex(t.expected));assert.ok(labParseResponse(payload(lines),q,'abc').passed);const missing=labParseResponse(payload(lines.slice(1)),q,'abc');assert.equal(missing.passed,false);assert.equal(missing.cases[0].missing,true);assert.equal(labParseResponse(payload(lines),q,'different').passed,false);const bad=payload([...lines]);bad.code=1;assert.equal(labParseResponse(bad,q,'abc').passed,false);bad.code=0;bad.timedOut=true;assert.equal(labParseResponse(bad,q,'abc').passed,false);bad.timedOut=false;bad.truncated=true;assert.equal(labParseResponse(bad,q,'abc').passed,false);});
test('Returned-value mismatch never passes, and ordinary output remains visible',()=>{const a=labParseResponse(payload(['<script>text</script>','@STUDY:abc|case1|PASS|'+hex('0')+'|'+hex('12')]),q,'abc');assert.equal(a.cases[0].passed,false);assert.equal(a.cases[0].actual,'0');assert.ok(a.stdout.includes('<script>text</script>'));});
test('Build failure and malformed responses remain failures',()=>{const a=labParseResponse({code:1,didExecute:false,buildResult:{code:1,stderr:[{text:"main.cpp:2:18: error: expected ';' before '}' token"}]}},q,'abc');assert.equal(a.compiled,false);assert.equal(a.passed,false);assert.equal(a.cases.filter(x=>x.missing).length,4);assert.ok(labDiagnosticHelp(a.diagnostics).includes('semicolon'));assert.throws(()=>labParseResponse({error:'unavailable'}));});
test('Normal run preserves stdout, stderr and nonzero exit status',()=>{const a=payload(['42']);a.stderr=[{text:'input rejected'}];a.code=2;const r=labParseResponse(a);assert.equal(r.stdout,'42');assert.equal(r.stderr,'input rejected');assert.equal(r.code,2);assert.equal(r.passed,false);});

test('Book I worked examples cover every complete source listing and mark adapters',()=>{const worked=sourceCoding().workedPrograms.filter(x=>x.courseId==='cpp-book-01');assert.equal(worked.length,86);assert.equal(new Set(worked.map(x=>x.sourceId)).size,86);assert.equal(worked.filter(x=>x.adapted).length,14);for(const w of worked){assert.ok(w.source.includes('int main(')||w.source.includes('int main()'));assert.ok(w.originalSource.length>0);assert.ok(w.checks.length>0);assert.equal(w.checks[0].stdout,w.sampleOutput);if(w.adapted)assert.ok(w.adaptationNote);else assert.equal(w.source,w.originalSource);}});
test('Book II worked examples cover all 84 C++ listings, including joined projects',()=>{const content=sourceData();const book=content.courses.find(c=>c.id==='cpp-book-02');const listings=book.series.listings.filter(x=>x.language==='cpp'),all=new Set(listings.map(x=>x.id)),byId=new Map(listings.map(x=>[x.id,x]));const worked=sourceCoding().workedPrograms.filter(x=>x.courseId==='cpp-book-02');assert.equal(worked.length,78);assert.equal(new Set(worked.map(x=>x.sourceId)).size,78);assert.deepEqual(new Set(worked.flatMap(x=>[x.sourceId,...x.sourcePartIds])),all);for(const w of worked){assert.ok(w.source.includes('int main(')||w.source.includes('int main()'));assert.equal(w.originalSource.trimEnd(),fs.readFileSync(new URL('../'+byId.get(w.sourceId).filename,import.meta.url),'utf8').trimEnd());assert.equal(w.checks[0].stdout,w.sampleOutput);if(w.adapted)assert.ok(w.adaptationNote);else assert.equal(w.source,w.originalSource);}});
test('Whole-program checker compares stdout, stderr, exit code and completion',()=>{const check={id:'case1',label:'Original',input:'7\n',stdout:'7\n',stderr:'',exitCode:0,hint:'Look at print.'},result={compiled:true,executed:true,code:0,stdout:'7',stderr:'',timedOut:false,truncated:false};assert.ok(labCheckWorkedResult(result,check).passed);assert.equal(labCheckWorkedResult({...result,stdout:'8'},check).passed,false);assert.equal(labCheckWorkedResult({...result,code:1},check).passed,false);assert.equal(labCheckWorkedResult({...result,stderr:'warning'},check).passed,false);assert.equal(labCheckWorkedResult({...result,executed:false},check).missing,true);assert.equal(labCheckWorkedResult({...result,timedOut:true},check).passed,false);assert.equal(labCheckWorkedResult({...result,stdout:'7 '},check).passed,false);});
