import {sourceData,sourceCoding} from '../scripts/read-source.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
const root=new URL('../',import.meta.url),data=sourceData(),books=data.courses.filter(c=>c.series),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const stable=x=>Array.isArray(x)?'['+x.map(stable).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}':JSON.stringify(x);
test('Existing approved curricula retain their full content',()=>{const before=JSON.parse(fs.readFileSync(new URL('docs/pre-series-approved.json',root)));for(const [id,digest] of Object.entries(before))assert.equal(hash(stable(data.courses.find(c=>c.id===id))),digest,id);});
test('All eight books and 186 chapters retain unique mapped source blocks',()=>{
 assert.equal(books.length,8);assert.equal(books.reduce((s,c)=>s+c.chapters.filter(x=>x.role==='chapter').length,0),186);
 for(const c of books){const topics=new Map(c.topics.map(t=>[t.id,t])),blocks=new Map(c.topics.flatMap(t=>t.blocks.map(b=>[b.id,b]))),mapped=[];
  assert.equal(topics.size,c.topics.length);assert.equal(blocks.size,c.series.counts.sourceBlocks);assert.equal(hash(c.topics.flatMap(t=>t.blocks.map(b=>b.text)).join('\n')),c.series.counts.sourceTextSHA256);
  for(const ch of c.chapters){const g=c.teaching[ch.number];assert.ok(topics.has(g.startTopicId));assert.ok(g.sections.length);for(const sec of g.sections)for(const id of sec.topics){assert.ok(topics.has(id));assert.equal(topics.get(id).sectionId,sec.id);assert.equal(topics.get(id).chapter,ch.number);mapped.push(id);}}
  assert.equal(new Set(mapped).size,mapped.length);assert.equal(mapped.length,c.topics.filter(t=>t.chapter>=0).length);
  const itemIds=new Set();for(const t of c.topics){for(const e of [...t.cards,...(t.practice||[])]){assert.ok(!itemIds.has(e.id));itemIds.add(e.id);}for(const e of t.practice||[]){assert.ok(topics.has(e.sourceTopicId));for(const id of [...e.promptBlocks,...e.answerBlocks])assert.ok(blocks.has(id));}}
  for(const target of Object.values(c.series.links)){assert.ok(topics.has(target.topicId));assert.ok(blocks.has(target.blockId));}
 }
});
test('Original PDF/EPUB downloads and 1482 extracted listings match packaged bytes',()=>{let total=0;for(const c of books){const blocks=new Map(c.topics.flatMap(t=>t.blocks.map(b=>[b.id,b])));for(const asset of Object.values(c.series.assets)){const bytes=fs.readFileSync(new URL('cpp_series/books/'+asset.name,root));assert.equal(hash(bytes),asset.sha256);assert.deepEqual(Buffer.from(asset.base64,'base64'),bytes);}for(const e of c.series.listings){total++;const bytes=fs.readFileSync(new URL(e.filename,root));assert.equal(hash(bytes),e.sha256);const code=blocks.get(e.blockId).code;assert.equal(bytes.toString(),code.endsWith('\n')?code:code+'\n');if(e.validation){assert.equal(e.validation.sha256,e.sha256);if(e.validation.status==='verified')assert.equal(e.validation.stdout,e.expectedExact);}}}assert.equal(total,1482);});
test('Eight diagrams use matching source excerpts, exact focus lines and live relationships',()=>{for(const c of books){assert.equal(Object.keys(c.diagrams).length,1);const d=c.diagrams['1'],source=fs.readFileSync(new URL(d.source,root),'utf8'),lines=source.split('\n'),flat=s=>s.replace(/\s/g,'');assert.equal(d.focus.length,2);for(const f of d.focus){assert.equal(f.file,d.source);assert.equal(f.code,lines.slice(f.lineStart-1,f.lineEnd).join('\n'));assert.equal(f.explain.length,f.lineEnd-f.lineStart+1);for(const field of ['what','where','why','invariant','risk'])assert.ok(f[field]);}const v=d.overview,ids=new Set(v.nodes.map(n=>n.id));assert.ok(v.image.startsWith('data:image/svg+xml;base64,'));for(const e of v.edges){assert.ok(ids.has(e.from)&&ids.has(e.to));}for(const n of v.nodes)for(const code of n.code.filter(s=>!s.trim().startsWith('//')))assert.ok(flat(source).includes(flat(code)),`${c.id}: ${code}`);}});
