cmake_minimum_required(VERSION 3.24)
project(HarborMetrics VERSION 0.1.0 LANGUAGES CXX)
include(CTest)
add_library(metrics STATIC ../metrics.cpp)
target_compile_features(metrics PUBLIC cxx_std_20)
target_include_directories(metrics PUBLIC "${CMAKE_CURRENT_LIST_DIR}/..")
add_executable(harbor-metrics ../main.cpp)
target_include_directories(harbor-metrics PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../../../support")
target_link_libraries(harbor-metrics PRIVATE metrics)
set_target_properties(metrics harbor-metrics PROPERTIES CXX_EXTENSIONS OFF)
add_test(NAME self_test COMMAND harbor-metrics --self-test)
add_test(NAME file_contract COMMAND harbor-metrics --input "${CMAKE_CURRENT_LIST_DIR}/../example.csv")
set_tests_properties(file_contract PROPERTIES PASS_REGULAR_EXPRESSION "count=3 total=12 min=-2 max=9 mean=4.000")
install(TARGETS harbor-metrics RUNTIME DESTINATION bin)
