"""Original Book I chapter exercises. q is the catalog's validated constructor."""

def add_book_one(q):
 c='cpp-book-01'
 q(c,'b1-sensor-sort','Sort sensor readings by value','Extend',
 'A sensor report should list values from largest to smallest. Return a sorted copy; keep the caller’s vector unchanged. Empty input stays empty.',
 'std::vector<int> descending(const std::vector<int>& readings)',
 'std::vector<int> descending(const std::vector<int>& readings) {\n    auto copy=readings;\n    std::sort(copy.begin(),copy.end()); // BUG: wrong order\n    return copy;\n}',
 'std::vector<int> descending(const std::vector<int>& readings) {\n    auto copy=readings;\n    std::sort(copy.begin(),copy.end(),std::greater<int>{});\n    return copy;\n}',
 'int main(){ std::vector<int> v; int n; while(std::cin>>n)v.push_back(n); for(int x:descending(v))std::cout<<x<<" "; std::cout<<"\\n"; }',
 ('3 8 1\n','8 3 1 \n'),
 [('Unsorted readings','descending({3,8,1})','[8, 3, 1]','The default sort order is increasing.'),('Duplicates','descending({4,4,9})','[9, 4, 4]','Keep both readings.'),('Empty','descending({})','[]','An empty range needs no special index.'),('Negative readings','descending({-7,-1,-4})','[-1, -4, -7]','Do not assume sensor values are positive.'),('Caller remains unchanged','([]{std::vector<int> v{3,1}; descending(v); return v==std::vector<int>{3,1};})()','true','Sort a copy, not the borrowed vector.')],
 ['std::sort takes two iterators that mark the start and end.','A greater-than comparison asks sort to put larger values first.'],
 'A const reference borrows readings without copying or changing them. The local copy owns the sorted values. This follows the chapter’s value-type sensor example.',chapter=1,includes=['iostream','vector','algorithm','functional'])
 q(c,'b1-standard','Read a C++ standard tag','Debug',
 'A build reports the numeric __cplusplus tag. Return true if it names C++20 or a later standard. An older or zero tag returns false. Do not depend on this compiler’s own tag while testing the function.',
 'bool supportsCxx20(long tag)',
 'bool supportsCxx20(long tag){ return tag>202002; // BUG: misses the exact C++20 tag\n}',
 'bool supportsCxx20(long tag){ return tag>=202002; }',
 'int main(){ long tag; if(!(std::cin>>tag))return 2; std::cout<<std::boolalpha<<supportsCxx20(tag)<<"\\n"; }',
 ('202002\n','true\n'),
 [('Exact C++20 tag','supportsCxx20(202002)','true','Include the boundary with >=.'),('Older C++17','supportsCxx20(201703)','false','A smaller tag is too old.'),('Later standard','supportsCxx20(202302)','true','Do not require exact equality.'),('Absent tag','supportsCxx20(0)','false','Zero is not a modern standard.')],
 ['Compare the numeric value, including the boundary.','>= means greater than or equal to.'],
 '__cplusplus is a compile-time macro in real code. Passing a numeric tag to a function lets a small unit test exercise the boundary independently.',chapter=2,includes=['iostream'])
 q(c,'b1-age','Validate age before calculating','Debug',
 'A user enters an age from 0 through 130. Return next year’s age; reject every other value with std::invalid_argument before doing arithmetic. The driver catches the error.',
 'int nextAge(int age)',
 'int nextAge(int age){ if(age>130)throw std::invalid_argument("invalid age"); return age+1; }',
 'int nextAge(int age){ if(age<0||age>130)throw std::invalid_argument("invalid age"); return age+1; }',
 'int main(){int age;if(!(std::cin>>age))return 2;try{std::cout<<nextAge(age)<<"\\n";}catch(const std::invalid_argument&){std::cout<<"invalid age\\n";}}',
 ('29\n','30\n'),
 [('Normal value','nextAge(29)','30','Return age plus one.'),('Age zero','nextAge(0)','1','Zero is in range.'),('Upper boundary','nextAge(130)','131','130 is still a valid input.'),('Negative rejected','([]{try{nextAge(-1);return false;}catch(const std::invalid_argument&){return true;}})()','true','Check the lower boundary.'),('Too old rejected','([]{try{nextAge(131);return false;}catch(const std::invalid_argument&){return true;}})()','true','Check the upper boundary.')],
 ['The rule is 0 <= age <= 130.','Reject a bad input before computing the return value.'],
 'The function owns validation. The driver owns terminal input and printing. A throw transfers control to the driver’s catch block.',chapter=3,includes=['iostream','stdexcept'])
 q(c,'b1-narrow','Check a narrowing conversion','Debug',
 'Convert a long long number to int only when the value fits. Otherwise throw std::out_of_range. The caller may catch it. Avoid casting before checking the bounds.',
 'int narrow(long long value)',
 'int narrow(long long value){ return static_cast<int>(value); // BUG: unchecked narrowing\n}',
 'int narrow(long long value){\n    if(value<std::numeric_limits<int>::min()||value>std::numeric_limits<int>::max())throw std::out_of_range("outside int range");\n    return static_cast<int>(value);\n}',
 'int main(){long long n;if(!(std::cin>>n))return 2;try{std::cout<<narrow(n)<<"\\n";}catch(const std::out_of_range&){std::cout<<"outside int range\\n";}}',
 ('42\n','42\n'),
 [('Small positive','narrow(42)','42','In-range values pass through.'),('Small negative','narrow(-11)','-11','Negative values also fit.'),('Maximum int','narrow(std::numeric_limits<int>::max())','2147483647','The maximum itself is valid on the documented x86-64 target.'),('Above maximum','([]{try{narrow(static_cast<long long>(std::numeric_limits<int>::max())+1);return false;}catch(const std::out_of_range&){return true;}})()','true','Compare before the cast.'),('Below minimum','([]{try{narrow(static_cast<long long>(std::numeric_limits<int>::min())-1);return false;}catch(const std::out_of_range&){return true;}})()','true','Check both ends of the range.')],
 ['std::numeric_limits<int> supplies the two int bounds.','A conversion after a successful range check keeps the value.'],
 'A narrowing conversion may lose information. The check makes the boundary part of the function’s contract rather than leaving a surprising result to the caller.',chapter=4,includes=['iostream','limits','stdexcept'])
 q(c,'b1-discount','Calculate a percentage discount','Guided',
 'A checkout applies a whole-number discount percent. subtotal is 0–1000 and percent is 0–100. Return the amount after discount, dropping any fractional cent from integer division. Reject values outside those bounds.',
 'int afterDiscount(int subtotal,int percent)',
 'int afterDiscount(int subtotal,int percent){ if(subtotal<0||subtotal>1000||percent<0||percent>100)throw std::invalid_argument("range"); return subtotal-percent; }',
 'int afterDiscount(int subtotal,int percent){ if(subtotal<0||subtotal>1000||percent<0||percent>100)throw std::invalid_argument("range"); return subtotal*(100-percent)/100; }',
 'int main(){int amount,percent;if(!(std::cin>>amount>>percent))return 2;try{std::cout<<afterDiscount(amount,percent)<<"\\n";}catch(const std::invalid_argument&){std::cout<<"range\\n";}}',
 ('120 10\n','108\n'),
 [('Ten percent','afterDiscount(120,10)','108','A percent is per hundred, not an amount of money.'),('Zero discount','afterDiscount(75,0)','75','Zero percent preserves the amount.'),('Full discount','afterDiscount(75,100)','0','One hundred percent removes it all.'),('Remainder rounded down','afterDiscount(99,15)','84','Integer division drops the fraction after multiplying.'),('Invalid percent','([]{try{afterDiscount(50,101);return false;}catch(const std::invalid_argument&){return true;}})()','true','Keep the stated input domain.')],
 ['First find the remaining percentage: 100 - percent.','Multiply before dividing by 100 for the required integer result.'],
 'The expression stays in int range under the stated limits. Parentheses show which amount is kept, and validation protects the assumption.',chapter=5,includes=['iostream','stdexcept'])
 q(c,'b1-shipping','Name the first shipping blocker','Debug',
 'Return "pay" if unpaid; otherwise "address" if the address is invalid; otherwise "stock" if stock is zero or less; otherwise "ready". The priority order is part of the contract.',
 'std::string shippingStatus(bool paid,bool addressValid,int stock)',
 'std::string shippingStatus(bool paid,bool addressValid,int stock){ if(paid&&addressValid&&stock>0)return "ready"; return "stock"; }',
 'std::string shippingStatus(bool paid,bool addressValid,int stock){ if(!paid)return "pay"; if(!addressValid)return "address"; if(stock<=0)return "stock"; return "ready"; }',
 'int main(){int p,a,s;if(!(std::cin>>p>>a>>s))return 2;std::cout<<shippingStatus(p!=0,a!=0,s)<<"\\n";}',
 ('1 1 4\n','ready\n'),
 [('Ready','shippingStatus(true,true,4)','ready','All three conditions are true.'),('Payment first','shippingStatus(false,false,0)','pay','Check payment before the other blockers.'),('Address next','shippingStatus(true,false,0)','address','Check the address before stock.'),('No stock','shippingStatus(true,true,0)','stock','Zero cannot fulfill an order.'),('Negative stock','shippingStatus(true,true,-2)','stock','Negative is not available stock.')],
 ['Test blockers in the required priority order.','Each early return ends the function, so later conditions are not consulted.'],
 'Named outcomes tell callers why work cannot continue. Order matters when several conditions fail at once.',chapter=6,includes=['iostream','string'])
 q(c,'b1-until-zero','Stop a reading loop at zero','Debug',
 'Sum only positive readings until the first zero. Ignore negative readings. Do not inspect readings after the zero marker. Inputs and sum fit in int.',
 'int positiveUntilZero(const std::vector<int>& readings)',
 'int positiveUntilZero(const std::vector<int>& readings){ int sum=0; for(int value:readings)sum+=value; return sum; }',
 'int positiveUntilZero(const std::vector<int>& readings){ int sum=0; for(int value:readings){ if(value==0)break; if(value<0)continue; sum+=value; } return sum; }',
 'int main(){std::vector<int> v;int n;while(std::cin>>n)v.push_back(n);std::cout<<positiveUntilZero(v)<<"\\n";}',
 ('2 -5 3 0 100\n','5\n'),
 [('Ignore negative','positiveUntilZero({2,-5,3})','5','Negative readings do not add to sum.'),('Stop at first zero','positiveUntilZero({2,3,0,100})','5','Use break when the marker arrives.'),('Marker first','positiveUntilZero({0,9})','0','Nothing after zero is visited.'),('Empty','positiveUntilZero({})','0','Start at zero.'),('Only positives','positiveUntilZero({1,2,3})','6','Count every positive value.')],
 ['break leaves the loop.','continue skips the rest of this iteration.'],
 'The loop moves from left to right. The zero sentinel changes control flow; it is not merely a value to add.',chapter=7,includes=['iostream','vector'])
 q(c,'b1-double-ref','Change the caller’s value','Guided',
 'Double a nonnegative value through an int reference. Input is 0–1000, so the result fits. The function returns void; the driver prints the changed caller value.',
 'void doubleValue(int& value)',
 'void doubleValue(int& value){ int copy=value*2; (void)copy; // BUG: caller still has the old value\n}',
 'void doubleValue(int& value){ value*=2; }',
 'int main(){int n;if(!(std::cin>>n))return 2;doubleValue(n);std::cout<<n<<"\\n";}',
 ('11\n','22\n'),
 [('Ordinary','([]{int n=11;doubleValue(n);return n;})()','22','Assign through the reference parameter.'),('Zero','([]{int n=0;doubleValue(n);return n;})()','0','Zero stays zero.'),('Upper input','([]{int n=1000;doubleValue(n);return n;})()','2000','The input bound keeps the result safe.'),('Same caller object','([]{int n=7;int& alias=n;doubleValue(alias);return n;})()','14','A reference names the caller’s object.')],
 ['int& means the function receives another name for the same int.','Changing a copy does not change the caller.'],
 'Pass by reference shares the object. A void function can still have an effect by changing the object it borrowed.',chapter=8,includes=['iostream'])
 q(c,'b1-ticket','Keep a local value across calls','Debug',
 'Issue sequential ticket numbers starting at 1. Keep the count across calls during one program run. No resets or concurrent calls are required; at most 1000 tickets are issued.',
 'int nextTicket()',
 'int nextTicket(){ int count=0; return ++count; // BUG: local count starts over\n}',
 'int nextTicket(){ static int count=0; return ++count; }',
 'int main(){std::cout<<nextTicket()<<" "<<nextTicket()<<" "<<nextTicket()<<"\\n";}',
 ('','1 2 3\n'),
 [('First ticket','nextTicket()','1','The first call should return 1.'),('Second ticket','nextTicket()','2','A regular local variable starts over each call.'),('Third ticket','nextTicket()','3','The saved count should keep increasing.'),('Fourth ticket','nextTicket()','4','The state should still be present.')],
 ['A static local is initialized once and lives for the rest of the process.','The static keyword belongs on the counter declaration, not the return value.'],
 'The function controls the counter. Its local name is hidden from callers while the stored value lasts between calls; this is single-threaded.',chapter=9,includes=['iostream'])
 q(c,'b1-extrema','Find both ends of a fixed array','Debug',
 'Return the smallest and largest values in a four-element std::array, in that order. Values may all be negative. Do not mutate the caller’s array.',
 'std::pair<int,int> extrema(const std::array<int,4>& values)',
 'std::pair<int,int> extrema(const std::array<int,4>& values){ int low=0,high=0; for(int x:values){if(x<low)low=x;if(x>high)high=x;}return {low,high}; }',
 'std::pair<int,int> extrema(const std::array<int,4>& values){ int low=values[0],high=values[0]; for(int x:values){if(x<low)low=x;if(x>high)high=x;}return {low,high}; }',
 'int main(){std::array<int,4> a{};for(int& x:a)if(!(std::cin>>x))return 2;auto [lo,hi]=extrema(a);std::cout<<lo<<" "<<hi<<"\\n";}',
 ('-8 -3 -12 -5\n','-12 -3\n'),
 [('All negative','extrema(std::array<int,4>{-8,-3,-12,-5})','(-12, -3)','Initialize both candidates from a real element.'),('All positive','extrema(std::array<int,4>{2,7,5,4})','(2, 7)','Zero is not necessarily an array element.'),('Repeated','extrema(std::array<int,4>{3,3,3,3})','(3, 3)','Equal values are both bounds.'),('Mixed','extrema(std::array<int,4>{0,-4,7,-1})','(-4, 7)','Inspect each value.')],
 ['A std::array<int,4> always has four elements.','Use values[0] as the first candidate because an empty case is impossible.'],
 'The min and max candidates are always values seen so far. The pair groups the two answers without changing input.',chapter=10,includes=['iostream','array','utility'])
 q(c,'b1-username','Extract a labeled user name','Debug',
 'Accept a string beginning exactly with "user:" followed by a nonempty name. Return the name. Reject other prefixes and empty names with std::invalid_argument. A colon inside the name is ordinary text.',
 'std::string userName(std::string_view record)',
 'std::string userName(std::string_view record){ return std::string(record.substr(5)); // BUG: no prefix check\n}',
 'std::string userName(std::string_view record){ if(!record.starts_with("user:")||record.size()==5)throw std::invalid_argument("user record"); return std::string(record.substr(5)); }',
 'int main(){std::string line;std::getline(std::cin,line);try{std::cout<<userName(line)<<"\\n";}catch(const std::invalid_argument&){std::cout<<"user record\\n";}}',
 ('user:charles\n','charles\n'),
 [('Simple record','userName("user:charles")','charles','Take the substring after the label.'),('Colon in name','userName("user:a:b")','a:b','Only the fixed leading label is special.'),('Wrong prefix','([]{try{userName("name:ada");return false;}catch(const std::invalid_argument&){return true;}})()','true','Check the complete prefix.'),('Empty name','([]{try{userName("user:");return false;}catch(const std::invalid_argument&){return true;}})()','true','The name must not be empty.'),('Too short','([]{try{userName("hi");return false;}catch(const std::invalid_argument&){return true;}})()','true','Validate before taking the substring.')],
 ['starts_with checks the exact first five characters.','After validation, substr(5) views characters from index 5 onward.'],
 'string_view borrows the caller’s text; constructing std::string makes a returned owner that remains valid after the caller changes.',chapter=11,includes=['iostream','string','string_view','stdexcept'])
 q(c,'b1-prefix-max','Keep the best value seen so far','Debug',
 'For each vector element, return the largest value seen up to that point. Return the same number of outputs as inputs. Empty input produces empty output. Inputs may be negative.',
 'std::vector<int> prefixMax(const std::vector<int>& values)',
 'std::vector<int> prefixMax(const std::vector<int>& values){ int best=0;std::vector<int> out;for(int x:values){if(x>best)best=x;out.push_back(best);}return out; }',
 'std::vector<int> prefixMax(const std::vector<int>& values){ std::vector<int> out;out.reserve(values.size());for(int x:values){if(out.empty()||x>out.back())out.push_back(x);else out.push_back(out.back());}return out; }',
 'int main(){std::vector<int> v;int n;while(std::cin>>n)v.push_back(n);for(int x:prefixMax(v))std::cout<<x<<" ";std::cout<<"\\n";}',
 ('-5 -2 -7 4\n','-5 -2 -2 4 \n'),
 [('Negative start','prefixMax({-5,-2,-7,4})','[-5, -2, -2, 4]','The first best value is the first input, not zero.'),('Empty','prefixMax({})','[]','Never access the first element of empty input.'),('Decreasing','prefixMax({9,7,3})','[9, 9, 9]','Keep the earlier best.'),('New high','prefixMax({1,3,2,6})','[1, 3, 3, 6]','Update best when you see a larger value.')],
 ['The last output element is the best so far.','An empty output means you have not seen any input yet.'],
 'The returned vector grows once per input value, preserving both order and count. It owns its storage independently of the input.',chapter=12,includes=['iostream','vector'])
 q(c,'b1-clamp-reference','Clamp through a reference','Debug',
 'Change the caller’s int into the closed interval [lower, upper]. If lower exceeds upper, throw std::invalid_argument without changing the caller. Inputs otherwise fit in int.',
 'void clamp(int& value,int lower,int upper)',
 'void clamp(int& value,int lower,int upper){ if(lower>upper)throw std::invalid_argument("bounds"); if(value<lower)lower=value; if(value>upper)upper=value; }',
 'void clamp(int& value,int lower,int upper){ if(lower>upper)throw std::invalid_argument("bounds"); if(value<lower)value=lower; else if(value>upper)value=upper; }',
 'int main(){int v,l,u;if(!(std::cin>>v>>l>>u))return 2;try{clamp(v,l,u);std::cout<<v<<"\\n";}catch(const std::invalid_argument&){std::cout<<"bounds\\n";}}',
 ('-4 0 10\n','0\n'),
 [('Below minimum','([]{int v=-4;clamp(v,0,10);return v;})()','0','Assign into the referenced value.'),('Above maximum','([]{int v=20;clamp(v,0,10);return v;})()','10','Assign into the referenced value.'),('Inside range','([]{int v=7;clamp(v,0,10);return v;})()','7','Leave an in-range value alone.'),('Invalid bounds preserve value','([]{int v=7;try{clamp(v,10,0);}catch(const std::invalid_argument&){}return v;})()','7','Reject before mutating.'),('Invalid bounds throw','([]{int v=5;try{clamp(v,10,0);return false;}catch(const std::invalid_argument&){return true;}})()','true','The declared invalid range must be rejected.')],
 ['int& value is another name for the caller’s int.','lower and upper are copies; assigning to them cannot change value.'],
 'The reference has no ownership. Its caller keeps the int alive for the call. Validate first to give failure a no-change guarantee.',chapter=13,includes=['iostream','stdexcept'])
 q(c,'b1-optional-pointer','Read a selected value safely','Debug',
 'A pointer may name an int or be null. Return the pointed-to value when present, otherwise return the caller’s fallback. Do not store the pointer or dereference null.',
 'int selectedValue(const int* selected,int fallback)',
 'int selectedValue(const int* selected,int fallback){ return selected?*selected:0; // BUG: ignores fallback\n}',
 'int selectedValue(const int* selected,int fallback){ return selected?*selected:fallback; }',
 'int main(){int has,value,fallback;if(!(std::cin>>has>>value>>fallback))return 2;std::cout<<selectedValue(has?&value:nullptr,fallback)<<"\\n";}',
 ('0 42 7\n','7\n'),
 [('Present pointer','([]{int x=42;return selectedValue(&x,7);})()','42','Read through the pointer only when nonnull.'),('Null uses fallback','selectedValue(nullptr,7)','7','Use the caller-supplied fallback.'),('Negative fallback','selectedValue(nullptr,-3)','-3','Do not hard-code zero.'),('Zero is valid pointed value','([]{int x=0;return selectedValue(&x,9);})()','0','Zero and absence are different states.')],
 ['Check a pointer before using * to read the object it points at.','nullptr means no object selected.'],
 'The pointer borrows an object. The function neither owns nor retains it. The caller must keep that int alive for the duration of the call.',chapter=14,includes=['iostream'])
 q(c,'b1-owned-reading','Return an owned reading','Guided',
 'For nonnegative input, allocate an int with std::make_unique and return its unique owner. Reject negative input with std::invalid_argument. The caller may move the owner and read its value.',
 'std::unique_ptr<int> makeReading(int value)',
 'std::unique_ptr<int> makeReading(int value){ return std::make_unique<int>(0); // BUG: loses value and validation\n}',
 'std::unique_ptr<int> makeReading(int value){ if(value<0)throw std::invalid_argument("negative reading"); return std::make_unique<int>(value); }',
 'int main(){int n;if(!(std::cin>>n))return 2;try{auto reading=makeReading(n);std::cout<<*reading<<"\\n";}catch(const std::invalid_argument&){std::cout<<"negative reading\\n";}}',
 ('42\n','42\n'),
 [('Owned value','*makeReading(42)','42','Construct with the input value.'),('Zero is allowed','*makeReading(0)','0','Zero is a valid reading.'),('Negative rejected','([]{try{makeReading(-1);return false;}catch(const std::invalid_argument&){return true;}})()','true','Validate before allocating.'),('Owner move','([]{auto a=makeReading(9);auto b=std::move(a);return !a&&*b==9;})()','true','A unique owner can be moved to another variable.')],
 ['make_unique<int>(value) constructs an owned int.','Moving a unique_ptr transfers the owner.'],
 'The unique_ptr owns the heap int and releases it at the end of its lifetime. No manual delete is required.',chapter=15,includes=['iostream','memory','stdexcept','utility'])
 q(c,'b1-state-record','Label a structured status','Debug',
 'A Reading has an id, a name, and a state. Return "id:name:queued", "id:name:running", or "id:name:done". Use the enum value; do not modify the record.',
 'std::string label(const Reading& reading)',
 'enum class State{queued,running,done};\nstruct Reading{int id;std::string name;State state;};\nstd::string label(const Reading& reading){return std::to_string(reading.id)+":"+reading.name+":queued";}',
 'enum class State{queued,running,done};\nstruct Reading{int id;std::string name;State state;};\nstd::string label(const Reading& reading){std::string suffix;switch(reading.state){case State::queued:suffix="queued";break;case State::running:suffix="running";break;case State::done:suffix="done";break;}return std::to_string(reading.id)+":"+reading.name+":"+suffix;}',
 'int main(){int id,code;std::string name;if(!(std::cin>>id>>name>>code))return 2;if(code<0||code>2)return 3;std::cout<<label({id,name,static_cast<State>(code)})<<"\\n";}',
 ('2 meter 1\n','2:meter:running\n'),
 [('Queued','label({1,"scope",State::queued})','1:scope:queued','This is the starter’s only correct state.'),('Running','label({2,"meter",State::running})','2:meter:running','Use the actual enum state.'),('Done','label({3,"camera",State::done})','3:camera:done','Handle the final enum case.'),('Empty name preserved','label({0,"",State::done})','0::done','Formatting preserves data even when the name is empty.')],
 ['A struct groups the id, name, and state.','A switch handles each enum class member by name.'],
 'The enum limits the set of intended states. The formatting function borrows the record as a const reference and creates an owned string.',chapter=16,includes=['iostream','string'])
 q(c,'b1-quantity','Keep a class nonnegative','Debug',
 'A Quantity begins at zero. add(amount) accepts only positive amounts and keeps the total at most 1000. take(amount) accepts only positive amounts no larger than the current total. Rejected calls return false without changing the total.',
 'class Quantity: bool add(int); bool take(int); int value() const',
 'class Quantity{int value_{};public:bool add(int amount){if(amount<=0||amount>1000-value_)return false;value_+=amount;return true;}bool take(int amount){value_-=amount;return true;}int value()const{return value_;}};',
 'class Quantity{int value_{};public:bool add(int amount){if(amount<=0||amount>1000-value_)return false;value_+=amount;return true;}bool take(int amount){if(amount<=0||amount>value_)return false;value_-=amount;return true;}int value()const{return value_;}};',
 'int main(){int add,take;if(!(std::cin>>add>>take))return 2;Quantity q;std::cout<<std::boolalpha<<q.add(add)<<" "<<q.take(take)<<" "<<q.value()<<"\\n";}',
 ('12 5\n','true true 7\n'),
 [('Add and take','([]{Quantity q;q.add(12);q.take(5);return q.value();})()','7','Take subtracts from the stored total.'),('Cannot overdraw','([]{Quantity q;q.add(3);return !q.take(4)&&q.value()==3;})()','true','Reject if taking more than is present.'),('Reject zero take','([]{Quantity q;q.add(3);return !q.take(0)&&q.value()==3;})()','true','The contract requires a positive amount.'),('Reject negative take','([]{Quantity q;q.add(3);return !q.take(-2)&&q.value()==3;})()','true','Do not let subtraction of a negative increase the total.'),('Capacity','([]{Quantity q;q.add(1000);return !q.add(1)&&q.value()==1000;})()','true','Keep the maximum limit.')],
 ['Check before changing private value_.','Return false on rejection without changing any stored state.'],
 'The class keeps its balance private, so callers cannot bypass add/take. Each method must preserve 0 <= value <= 1000.',chapter=17,includes=['iostream'])
 q(c,'b1-lifetime','Repair scope-based cleanup','Debug',
 'Track how many LiveToken objects exist. Construction adds one; destruction removes one. Copying is disabled, so each token has exactly one end. Single-threaded use only.',
 'class LiveToken: inline static int live; constructor; destructor; deleted copy',
 'class LiveToken{public:inline static int live=0;LiveToken(){++live;}~LiveToken(){}LiveToken(const LiveToken&)=delete;LiveToken& operator=(const LiveToken&)=delete;};',
 'class LiveToken{public:inline static int live=0;LiveToken(){++live;}~LiveToken(){--live;}LiveToken(const LiveToken&)=delete;LiveToken& operator=(const LiveToken&)=delete;};',
 'int main(){std::cout<<LiveToken::live<<" ";{LiveToken first,second;std::cout<<LiveToken::live<<" ";}std::cout<<LiveToken::live<<"\\n";}',
 ('','0 2 0\n'),
 [('Initially empty','LiveToken::live','0','No token has been constructed.'),('One live in scope','([]{LiveToken t;return LiveToken::live;})()','1','Construction increases count while the object exists.'),('After first scope','LiveToken::live','0','Destruction at the closing brace must decrease count.'),('Two in scope','([]{LiveToken a,b;return LiveToken::live;})()','2','Each object constructs once.'),('After second scope','LiveToken::live','0','Both destructors run after leaving scope.')],
 ['A destructor runs automatically at the end of an object’s lifetime.','Decrement the shared count exactly once in the destructor.'],
 'The live count is a teaching model for lifetime. The object owns one count contribution until destruction, including during exception unwinding.',chapter=18,includes=['iostream'])
 q(c,'b1-group-contract','Implement a declared module contract','Debug',
 'The declaration promises groups_needed(items, capacity). Return -1 for negative items or nonpositive capacity. Otherwise count groups of size capacity, rounding upward. Avoid an addition that might overflow int. Inputs fit in int.',
 'int groups_needed(int items,int capacity)',
 'int groups_needed(int items,int capacity);\nint groups_needed(int items,int capacity){if(items<0||capacity<=0)return -1;return items/capacity;}',
 'int groups_needed(int items,int capacity);\nint groups_needed(int items,int capacity){if(items<0||capacity<=0)return -1;return items/capacity+(items%capacity!=0);}',
 'int main(){int n,cap;if(!(std::cin>>n>>cap))return 2;std::cout<<groups_needed(n,cap)<<"\\n";}',
 ('23 5\n','5\n'),
 [('Remainder needs another group','groups_needed(23,5)','5','A nonzero remainder needs one extra group.'),('Exact fit','groups_needed(20,5)','4','Do not add one when there is no remainder.'),('Zero items','groups_needed(0,5)','0','No work needs no group.'),('Bad capacity','groups_needed(3,0)','-1','Reject before division.'),('Largest int capacity one','groups_needed(std::numeric_limits<int>::max(),1)','2147483647','Avoid items + capacity - 1 overflow.'),('Negative items','groups_needed(-1,5)','-1','Validate the count.')],
 ['An int declaration gives the caller the signature; the definition supplies the body.','Use quotient plus (remainder != 0) after checking capacity.'],
 'A multi-file build compiles declarations and definitions in separate translation units, then links them. This single-file lab exercises the same signature and behavior; the book’s original project teaches the physical file split.',chapter=19,includes=['iostream','limits'])
 q(c,'b1-inventory','Preserve every inventory rule','Extend',
 'Implement the book’s inventory contract: positive unique id, nonempty name, quantity from 0 to 1000, and at most 100 records. Rejected adds return false and leave every record unchanged. total returns a long long sum; successful records keep insertion order.',
 'class Inventory: bool add(Record); long long total() const; const std::vector<Record>& records() const',
 'struct Record{int id;std::string name;int quantity;};\nclass Inventory{std::vector<Record> records_;public:bool add(Record r){records_.push_back(std::move(r));return true;}long long total()const{long long n=0;for(const auto& r:records_)n+=r.quantity;return n;}const std::vector<Record>& records()const{return records_;}};',
 'struct Record{int id;std::string name;int quantity;};\nclass Inventory{std::vector<Record> records_;public:bool add(Record r){if(r.id<=0||r.name.empty()||r.quantity<0||r.quantity>1000||records_.size()>=100)return false;for(const auto& item:records_)if(item.id==r.id)return false;records_.push_back(std::move(r));return true;}long long total()const{long long n=0;for(const auto& r:records_)n+=r.quantity;return n;}const std::vector<Record>& records()const{return records_;}};',
 'int main(){Inventory store;int id,quantity;std::string name;while(std::cin>>id>>name>>quantity)store.add({id,name,quantity});std::cout<<store.records().size()<<" "<<store.total()<<"\\n";}',
 ('1 scope 2\n2 meter 3\n1 duplicate 4\n','2 5\n'),
 [('Accept two records','([]{Inventory s;return s.add({1,"scope",2})&&s.add({2,"meter",3})&&s.total()==5;})()','true','Add valid distinct ids.'),
  ('Duplicate rejected','([]{Inventory s;s.add({1,"first",2});return !s.add({1,"again",9})&&s.records().size()==1&&s.total()==2;})()','true','Search existing ids before pushing.'),
  ('Negative quantity rejected','([]{Inventory s;return !s.add({5,"bad",-1})&&s.records().empty();})()','true','Check quantity before changing state.'),
  ('Quantity over 1000 rejected','([]{Inventory s;return !s.add({5,"bad",1001})&&s.records().empty();})()','true','The inclusive upper bound is 1000.'),
  ('Positive id required','([]{Inventory s;return !s.add({0,"bad",1})&&!s.add({-1,"bad",1})&&s.records().empty();})()','true','Identifiers must be greater than zero.'),
  ('Nonempty name','([]{Inventory s;return !s.add({2,"",1})&&s.records().empty();})()','true','An empty name is rejected.'),
  ('Hundred-record cap','([]{Inventory s;for(int i=1;i<=100;++i)if(!s.add({i,"ok",1}))return false;return !s.add({101,"too many",1})&&s.records().size()==100&&s.total()==100;})()','true','Check the count before appending.'),
  ('Zero accepted and insertion order','([]{Inventory s;s.add({3,"a",0});s.add({1,"b",2});return s.records()[0].id==3&&s.records()[1].id==1&&s.total()==2;})()','true','Zero is allowed; accepted records append in call order.')],
 ['Validate every input rule before pushing to the vector.','The size limit is 100; search existing records for the id.'],
 'The book separates Record and Inventory into a header and implementation. This single-file lab tests that same contract. The class owns its vector; every rejection preserves it unchanged.',chapter=20,includes=['iostream','string','vector','utility'])
