"""One independent C++20 challenge for each core Book II chapter.

Each starter compiles but violates a stated rule. The driver is a complete
program only after it is joined to starter.cpp or solution.cpp.
"""

def add_book_two(q):
    def Q(ch, slug, title, level, requirement, signature, starter, solution,
          driver, sample, cases, hints, theory, includes):
        q('cpp-book-02', 'b2-'+slug, title, level, requirement, signature,
          starter, solution, driver, sample, cases, hints, theory,
          chapter=ch, includes=includes)

    Q(1,'value-copy','Return an independent value snapshot','Guided',
      'Copy all readings into a new vector, add delta to each copied value, and return it. Inputs and results fit int. The caller’s original vector must not change, including when it is empty.',
      'std::vector<int> shifted(const std::vector<int>& readings, int delta)',
      'std::vector<int> shifted(const std::vector<int>& readings,int delta){return readings;}',
      'std::vector<int> shifted(const std::vector<int>& readings,int delta){auto result=readings;for(int& value:result)value+=delta;return result;}',
      'int main(){int delta,n;if(!(std::cin>>delta>>n)||n<0)return 2;std::vector<int> v;for(int i=0,x;i<n;++i){if(!(std::cin>>x))return 2;v.push_back(x);}for(int x:shifted(v,delta))std::cout<<x<<" ";std::cout<<"\\n";}',
      ('3 3 1 4 7\n','4 7 10 \n'),
      [('Shift three','shifted({1,4,7},3)==std::vector<int>({4,7,10})','true','Change each item in the copy.'),
       ('Negative delta','shifted({-2,2},-3)==std::vector<int>({-5,-1})','true','A negative delta is valid.'),
       ('Empty remains empty','shifted({},5).empty()','true','No special object needs to be created.'),
       ('Original stays put','([]{std::vector<int> x{8};auto y=shifted(x,1);y[0]=100;return x[0]==8;})()','true','The returned vector owns its own elements.')],
      ['Copy the vector before the loop.','A reference in for(int& value:result) lets the loop change that copied element.'],
      'A vector copy has its own element storage. A const reference only borrows input. The caller still owns its original after the function returns.',
      ['iostream','vector'])
    Q(2,'dimension','Protect a class invariant','Debug',
      'Dimension stores a positive size. Its constructor rejects zero or negative values with std::invalid_argument; set does the same and leaves the old value untouched. The value() observer never changes the object.',
      'class Dimension: constructor(int), void set(int), int value() const',
      'class Dimension{int value_;public:explicit Dimension(int n):value_(n){}void set(int n){value_=n;}int value()const{return value_;}};',
      'class Dimension{int value_;public:explicit Dimension(int n):value_(n){if(n<=0)throw std::invalid_argument("dimension");}void set(int n){if(n<=0)throw std::invalid_argument("dimension");value_=n;}int value()const{return value_;}};',
      'int main(){int first,second;if(!(std::cin>>first>>second))return 2;try{Dimension d(first);d.set(second);std::cout<<d.value()<<"\\n";}catch(const std::invalid_argument&){std::cout<<"invalid dimension\\n";}}',
      ('4 7\n','7\n'),
      [('Construct valid','Dimension(4).value()','4','Store the positive constructor argument.'),
       ('Reject zero constructor','([]{try{Dimension d(0);return false;}catch(const std::invalid_argument&){return true;}})()','true','Reject before callers can use an invalid object.'),
       ('Reject negative constructor','([]{try{Dimension d(-4);return false;}catch(const std::invalid_argument&){return true;}})()','true','Positive excludes negative.'),
       ('Failed set keeps value','([]{Dimension d(5);try{d.set(0);}catch(const std::invalid_argument&){}return d.value()==5;})()','true','Validate before assigning.'),
       ('Successful set','([]{Dimension d(2);d.set(9);return d.value();})()','9','Allow a valid update.')],
      ['Put the check before the assignment.','A constructor can throw to stop an invalid object from being used.'],
      'The invariant is value_ > 0 after every successful operation. A rejected update has no visible change. const on value() promises not to edit the Dimension.',
      ['iostream','stdexcept'])
    Q(3,'scope-exit','Run a cleanup action once at scope exit','Ownership',
      'ScopeExit owns a cleanup function. Run it once when the guard is destroyed unless dismiss() was called. Disable copying so two guards cannot run the same cleanup. Single-threaded use; the callback is assumed not to throw.',
      'class ScopeExit: constructor(std::function<void()>), destructor, void dismiss()',
      'class ScopeExit{std::function<void()> fn_;bool active_=true;public:explicit ScopeExit(std::function<void()> f):fn_(std::move(f)){}~ScopeExit(){}ScopeExit(const ScopeExit&)=delete;ScopeExit& operator=(const ScopeExit&)=delete;void dismiss(){active_=false;}};',
      'class ScopeExit{std::function<void()> fn_;bool active_=true;public:explicit ScopeExit(std::function<void()> f):fn_(std::move(f)){}~ScopeExit(){if(active_)fn_();}ScopeExit(const ScopeExit&)=delete;ScopeExit& operator=(const ScopeExit&)=delete;void dismiss(){active_=false;}};',
      'int main(){int count=0;{ScopeExit guard([&]{++count;});}std::cout<<count<<"\\n";}',
      ('','1\n'),
      [('Normal scope','([]{int n=0;{ScopeExit g([&]{++n;});}return n;})()','1','The destructor runs as the guard leaves scope.'),
       ('Dismissed guard','([]{int n=0;{ScopeExit g([&]{++n;});g.dismiss();}return n;})()','0','Dismiss disables the action.'),
       ('Two guards','([]{int n=0;{ScopeExit a([&]{++n;});ScopeExit b([&]{++n;});}return n;})()','2','Each guard owns its own action.'),
       ('Exception unwinding','([]{int n=0;try{ScopeExit g([&]{++n;});throw 7;}catch(int){}return n;})()','1','A destructor also runs when a stack frame unwinds.')],
      ['The destructor is called automatically as the object ends.','Check active_ before invoking the owned callable.'],
      'Resource acquisition is initialization (RAII): a local owner ties cleanup to its own lifetime. This guard models cleanup without a manual call on every return path.',
      ['iostream','functional','utility'])
    Q(4,'snapshot-copy','Repair a shallow snapshot copy','Debug',
      'A Snapshot copied from another must own independent readings. set(0,v) changes only that snapshot. Indexes passed to get/set are valid; copying an empty Snapshot is valid.',
      'class Snapshot: Snapshot(vector<int>), int get(size_t) const, void set(size_t,int)',
      'class Snapshot{std::shared_ptr<std::vector<int>> values_;public:explicit Snapshot(std::vector<int> v):values_(std::make_shared<std::vector<int>>(std::move(v))){}int get(std::size_t i)const{return values_->at(i);}void set(std::size_t i,int v){values_->at(i)=v;}std::size_t size()const{return values_->size();}};',
      'class Snapshot{std::vector<int> values_;public:explicit Snapshot(std::vector<int> v):values_(std::move(v)){}int get(std::size_t i)const{return values_.at(i);}void set(std::size_t i,int v){values_.at(i)=v;}std::size_t size()const{return values_.size();}};',
      'int main(){Snapshot first({1,2});Snapshot second=first;second.set(0,9);std::cout<<first.get(0)<<" "<<second.get(0)<<"\\n";}',
      ('','1 9\n'),
      [('Copy independence','([]{Snapshot a({1,2});Snapshot b=a;b.set(0,9);return a.get(0)==1&&b.get(0)==9;})()','true','The copy must have its own elements.'),
       ('Assignment independence','([]{Snapshot a({3});Snapshot b({8});b=a;b.set(0,7);return a.get(0)==3&&b.get(0)==7;})()','true','Copy assignment must also be independent.'),
       ('Empty copy','([]{Snapshot a({});Snapshot b=a;return b.size()==0;})()','true','An empty vector can be copied.'),
       ('Original can change','([]{Snapshot a({5});Snapshot b=a;a.set(0,6);return b.get(0)==5;})()','true','Independence goes in both directions.')],
      ['std::shared_ptr copies share one vector.','A vector held by value already knows how to make independent copies.'],
      'The compiler-generated vector copy copies elements. A shared_ptr copy copies an owner of the same vector instead, which breaks a value-snapshot promise.',
      ['iostream','vector','memory','utility','cstddef'])
    Q(5,'ticket-move','Transfer a movable ticket','Ownership',
      'Ticket is move-only. Moving one Ticket transfers its positive identifier to the destination and sets the source identifier to zero. Both moving construction and moving assignment must work, including self-move. Copying stays disabled.',
      'class Ticket: move constructor noexcept, move assignment noexcept, int id() const',
      'class Ticket{int id_;public:explicit Ticket(int n):id_(n){}Ticket(const Ticket&)=delete;Ticket& operator=(const Ticket&)=delete;Ticket(Ticket&& other)noexcept:id_(other.id_){}Ticket& operator=(Ticket&& other)noexcept{id_=other.id_;return *this;}int id()const{return id_;}};',
      'class Ticket{int id_;public:explicit Ticket(int n):id_(n){}Ticket(const Ticket&)=delete;Ticket& operator=(const Ticket&)=delete;Ticket(Ticket&& other)noexcept:id_(std::exchange(other.id_,0)){}Ticket& operator=(Ticket&& other)noexcept{if(this!=&other)id_=std::exchange(other.id_,0);return *this;}int id()const{return id_;}};',
      'int main(){int id;if(!(std::cin>>id))return 2;Ticket first(id),second(std::move(first));std::cout<<first.id()<<" "<<second.id()<<"\\n";}',
      ('7\n','0 7\n'),
      [('Move construction','([]{Ticket a(4);Ticket b(std::move(a));return a.id()==0&&b.id()==4;})()','true','Clear the source as the destination takes its id.'),
       ('Move assignment','([]{Ticket a(4),b(5);b=std::move(a);return a.id()==0&&b.id()==4;})()','true','Assignment must transfer too.'),
       ('Self move','([]{Ticket a(9);a=std::move(a);return a.id()==9;})()','true','Check whether source and destination are the same object.'),
       ('Zero is moved-from state','([]{Ticket a(1);Ticket b(std::move(a));Ticket c(std::move(a));return c.id()==0&&b.id()==1;})()','true','An already moved-from Ticket holds zero.')],
      ['std::exchange(other.id_,0) returns the old id and replaces it with zero.','For move assignment, handle the same object on both sides.'],
      'std::move marks a source as eligible to move; the move member performs the transfer. noexcept states that the transfer itself does not throw.',
      ['iostream','utility'])
    Q(6,'parent-observer','Break an ownership cycle with a weak parent link','Ownership',
      'A parent owns each child through children. A child remembers its parent without owning it. makeChild registers one child and returns it. When the last external parent owner goes away, both objects must be destroyable.',
      'struct Node: weak_ptr<Node> parent; vector<shared_ptr<Node>> children; makeChild(shared_ptr<Node>)',
      'struct Node{std::weak_ptr<Node> parent;std::shared_ptr<Node> parentOwner;std::vector<std::shared_ptr<Node>> children;};std::shared_ptr<Node> makeChild(const std::shared_ptr<Node>& parent){auto child=std::make_shared<Node>();child->parent=parent;child->parentOwner=parent;parent->children.push_back(child);return child;}',
      'struct Node{std::weak_ptr<Node> parent;std::vector<std::shared_ptr<Node>> children;};std::shared_ptr<Node> makeChild(const std::shared_ptr<Node>& parent){auto child=std::make_shared<Node>();child->parent=parent;parent->children.push_back(child);return child;}',
      'int main(){auto parent=std::make_shared<Node>();auto child=makeChild(parent);std::cout<<parent->children.size()<<" "<<static_cast<bool>(child->parent.lock())<<"\\n";}',
      ('','1 1\n'),
      [('Registered child','([]{auto p=std::make_shared<Node>();auto c=makeChild(p);return p->children.size()==1&&p->children[0]==c;})()','true','Parent owns the child.'),
       ('Parent visible','([]{auto p=std::make_shared<Node>();auto c=makeChild(p);return c->parent.lock()==p;})()','true','A weak parent link can be locked while parent exists.'),
       ('Cycle releases','([]{std::weak_ptr<Node> witness;{auto p=std::make_shared<Node>();auto c=makeChild(p);witness=p;}return witness.expired();})()','true','Do not have child keep its parent alive.'),
       ('Child survives alone','([]{auto p=std::make_shared<Node>();auto c=makeChild(p);p.reset();return c->parent.expired();})()','true','A live child must notice a departed parent.')],
      ['shared_ptr adds ownership; weak_ptr observes without adding ownership.','The parent’s vector owns children; children should not own their parent.'],
      'A strong cycle cannot reach an owner count of zero by itself. A weak back-reference breaks that cycle while allowing a checked lock() when the parent still exists.',
      ['iostream','memory','vector'])
    Q(7,'money-add','Make addition behave like a value','Debug',
      'Money stores cents. Adding two amounts returns a new Money whose cents equal the sum. Neither operand changes. All tested sums fit in int. Equality compares cents.',
      'class Money: friend Money operator+(Money,Money); int cents() const',
      'class Money{int cents_;public:explicit Money(int n):cents_(n){}int cents()const{return cents_;}friend Money operator+(Money a,Money b){return Money(a.cents_-b.cents_);}friend bool operator==(Money a,Money b){return a.cents_==b.cents_;}};',
      'class Money{int cents_;public:explicit Money(int n):cents_(n){}int cents()const{return cents_;}friend Money operator+(Money a,Money b){return Money(a.cents_+b.cents_);}friend bool operator==(Money a,Money b){return a.cents_==b.cents_;}};',
      'int main(){int a,b;if(!(std::cin>>a>>b))return 2;std::cout<<(Money(a)+Money(b)).cents()<<"\\n";}',
      ('125 75\n','200\n'),
      [('Two positive','(Money(125)+Money(75)).cents()','200','Use addition for the new amount.'),
       ('Negative cents','(Money(10)+Money(-3)).cents()','7','Both signed amounts matter.'),
       ('Operands remain','([]{Money a(3),b(4);auto c=a+b;return a.cents()==3&&b.cents()==4&&c==Money(7);})()','true','Return a new value.'),
       ('Zero identity','Money(0)+Money(8)==Money(8)','true','Adding zero changes nothing.')],
      ['The + operator can be defined for a class if its meaning is clear.','Return a new Money value rather than changing either input.'],
      'The operator is a function called by a+b. Here friend gives it access to the private stored cents; pass-by-value keeps the operands independent.',
      ['iostream'])
    Q(8,'derived-state','Initialize the base part of a derived object','Debug',
      'Device stores a positive id; Meter derives from Device and adds a nonnegative reading. The Meter constructor must pass its id to Device. Inputs satisfy those domains.',
      'class Device(int id); class Meter : public Device(int id,int reading)',
      'class Device{int id_;public:explicit Device(int id):id_(id){}int id()const{return id_;}};class Meter:public Device{int reading_;public:Meter(int id,int reading):Device(1),reading_(reading){}int reading()const{return reading_;}};',
      'class Device{int id_;public:explicit Device(int id):id_(id){}int id()const{return id_;}};class Meter:public Device{int reading_;public:Meter(int id,int reading):Device(id),reading_(reading){}int reading()const{return reading_;}};',
      'int main(){int id,value;if(!(std::cin>>id>>value))return 2;Meter m(id,value);std::cout<<m.id()<<" "<<m.reading()<<"\\n";}',
      ('8 17\n','8 17\n'),
      [('Id goes to base','Meter(8,17).id()','8','Initialize Device from the received id.'),
       ('Reading belongs to meter','Meter(8,17).reading()','17','Keep the derived field.'),
       ('Second id','Meter(12,0).id()','12','Do not hard-code one base id.'),
       ('Independent instances','([]{Meter a(2,4),b(3,5);return a.id()==2&&b.id()==3&&a.reading()==4&&b.reading()==5;})()','true','Each object has its own base and derived data.')],
      ['A derived object contains a base subobject.','The colon after the constructor names the base constructor to call.'],
      'Device is built before the Meter fields. The base constructor receives the original id through the initializer list; no temporary or duplicate id is needed.',
      ['iostream'])
    Q(9,'runtime-area','Dispatch through a base reference','Polymorphism',
      'A Shape reference to a Rectangle must call Rectangle::area, returning width × height. Keep a virtual destructor because clients may delete through a base pointer. Width and height are nonnegative and the product fits int.',
      'class Shape: virtual int area() const; class Rectangle: override area()',
      'struct Shape{virtual ~Shape()=default;virtual int area()const{return 0;}};class Rectangle:public Shape{int w_,h_;public:Rectangle(int w,int h):w_(w),h_(h){}int area()const override{return 0;}};',
      'struct Shape{virtual ~Shape()=default;virtual int area()const=0;};class Rectangle:public Shape{int w_,h_;public:Rectangle(int w,int h):w_(w),h_(h){}int area()const override{return w_*h_;}};',
      'int main(){int w,h;if(!(std::cin>>w>>h))return 2;Rectangle r(w,h);const Shape& shape=r;std::cout<<shape.area()<<"\\n";}',
      ('3 5\n','15\n'),
      [('Base reference','([]{Rectangle r(3,5);const Shape& s=r;return s.area();})()','15','The virtual call needs derived behavior.'),
       ('Zero width','Rectangle(0,9).area()','0','Zero is a valid dimension.'),
       ('Another rectangle','Rectangle(4,7).area()','28','Use both fields.'),
       ('Base owner','([]{std::unique_ptr<Shape> p=std::make_unique<Rectangle>(2,6);return p->area();})()','12','A base owner needs virtual dispatch and safe deletion.')],
      ['virtual tells C++ to select behavior using the actual object type.','override checks that the derived signature really replaces a virtual function.'],
      'The call through Shape selects Rectangle at execution. A virtual base destructor ensures the derived destructor runs if a Shape pointer owns a Rectangle.',
      ['iostream','memory'])
    Q(10,'logging-component','Log one real state transition','Composition',
      'Controller borrows an Audit interface. start turns a stopped controller on and logs "started" exactly once. Further start calls return false without a log. stop turns it off without logging. The Audit reference must outlive Controller.',
      'class Audit; class Controller: bool start(), void stop(), bool running() const',
      'struct Audit{virtual ~Audit()=default;virtual void record(std::string_view)=0;};class Controller{Audit& log_;bool running_=false;public:explicit Controller(Audit& a):log_(a){}bool start(){log_.record("started");if(running_)return false;running_=true;return true;}void stop(){running_=false;}bool running()const{return running_;}};',
      'struct Audit{virtual ~Audit()=default;virtual void record(std::string_view)=0;};class Controller{Audit& log_;bool running_=false;public:explicit Controller(Audit& a):log_(a){}bool start(){if(running_)return false;running_=true;log_.record("started");return true;}void stop(){running_=false;}bool running()const{return running_;}};',
      'struct Capture:Audit{int calls=0;void record(std::string_view s)override{if(s=="started")++calls;}};int main(){Capture log;Controller c(log);c.start();c.start();std::cout<<std::boolalpha<<c.running()<<" "<<log.calls<<"\\n";}',
      ('','true 1\n'),
      [('First start','([]{struct C:Audit{int n=0;void record(std::string_view){++n;}} a;Controller c(a);return c.start()&&c.running()&&a.n==1;})()','true','Change state once and send one event.'),
       ('Second start quiet','([]{struct C:Audit{int n=0;void record(std::string_view){++n;}} a;Controller c(a);c.start();return !c.start()&&a.n==1;})()','true','Reject duplicate work before logging.'),
       ('Stop and restart','([]{struct C:Audit{int n=0;void record(std::string_view){++n;}} a;Controller c(a);c.start();c.stop();return !c.running()&&c.start()&&a.n==2;})()','true','A new transition after stop can log.'),
       ('No startup log','([]{struct C:Audit{int n=0;void record(std::string_view){++n;}} a;Controller c(a);return !c.running()&&a.n==0;})()','true','Construction does not start the controller.')],
      ['Check running_ before calling record.','A reference borrows the logger; it does not create or destroy it.'],
      'Composition lets a Controller use a supplied component. Its state transition decides when to call that component, so a rejected repeat cannot create a false audit event.',
      ['iostream','string_view'])
    Q(11,'generic-maximum','Choose the greater value for several types','Generic',
      'Implement maximum for two values of one type with operator<. Return either input by value. If tied, return the first. Use it for int and std::string; there is no mixed-type overload.',
      'template<class T> T maximum(T a,T b)',
      'template<class T>T maximum(T a,T b){return a;}',
      'template<class T>T maximum(T a,T b){return a<b?b:a;}',
      'int main(){int a,b;if(!(std::cin>>a>>b))return 2;std::cout<<maximum(a,b)<<"\\n";}',
      ('3 7\n','7\n'),
      [('Integers','maximum(3,7)','7','Compare both arguments.'),
       ('Negative integers','maximum(-8,-3)','-3','Zero is not an input here.'),
       ('Strings','maximum(std::string("alpha"),std::string("beta"))','beta','The same template must instantiate for strings.'),
       ('Tie','maximum(9,9)','9','An equal pair returns its value.')],
      ['The compiler makes a separate version for each used type.','Return b when a<b; otherwise return a.'],
      'template<class T> describes a type slot resolved at compilation. Instantiation needs operator< on T. Return-by-value keeps the answer after the local parameters end.',
      ['iostream','string'])
    Q(12,'bounded-stack','Make a reusable bounded stack','Generic',
      'Stack<T> has a constructor capacity. push returns false without changing state when full. pop returns the newest item or std::nullopt when empty. It works for int and string; zero capacity is valid. This small exercise assumes T can be copied.',
      'template<class T> class Stack: push(T), optional<T> pop(), size() const',
      'template<class T>class Stack{std::vector<T> values_;std::size_t cap_;public:explicit Stack(std::size_t c):cap_(c){}bool push(T value){values_.push_back(std::move(value));return true;}std::optional<T> pop(){if(values_.empty())return std::nullopt;T item=values_.back();values_.pop_back();return item;}std::size_t size()const{return values_.size();}};',
      'template<class T>class Stack{std::vector<T> values_;std::size_t cap_;public:explicit Stack(std::size_t c):cap_(c){}bool push(T value){if(values_.size()>=cap_)return false;values_.push_back(std::move(value));return true;}std::optional<T> pop(){if(values_.empty())return std::nullopt;T item=values_.back();values_.pop_back();return item;}std::size_t size()const{return values_.size();}};',
      'int main(){Stack<int> s(2);int x;while(std::cin>>x)s.push(x);while(auto v=s.pop())std::cout<<*v<<" ";std::cout<<"\\n";}',
      ('1 2 3\n','2 1 \n'),
      [('Last in first out','([]{Stack<int> s(2);s.push(1);s.push(2);return s.pop()==2&&s.pop()==1&&!s.pop();})()','true','Remove from the back.'),
       ('Full preserves size','([]{Stack<int> s(1);return s.push(4)&&!s.push(5)&&s.size()==1&&s.pop()==4;})()','true','Test capacity before adding.'),
       ('Empty zero capacity','([]{Stack<int> s(0);return !s.push(1)&&!s.pop()&&s.size()==0;})()','true','Zero means no room.'),
       ('String element','([]{Stack<std::string> s(1);return s.push("hi")&&s.pop()==std::optional<std::string>{"hi"};})()','true','T is not fixed to int.')],
      ['vector stores elements of whatever type T names.','Compare size() with cap_ before push_back.'],
      'The template defines one container rule for several value types. optional marks an empty pop without inventing a fake T value. The vector belongs to the Stack.',
      ['iostream','vector','optional','string','utility','cstddef'])
    Q(13,'safe-midpoint','Constrain safe midpoint arithmetic','Generic',
      'midpoint accepts one integral type except bool, following std::midpoint: return the middle value rounded toward the first argument for odd distances. It must avoid signed overflow, even at int limits.',
      'template<std::integral T> T midpoint(T a,T b) except bool',
      'template<std::integral T>requires(!std::same_as<T,bool>)T midpoint(T a,T b){return (a+b)/2;}',
      'template<std::integral T>requires(!std::same_as<T,bool>)T midpoint(T a,T b){return std::midpoint(a,b);}',
      'int main(){int a,b;if(!(std::cin>>a>>b))return 2;std::cout<<midpoint(a,b)<<"\\n";}',
      ('7 10\n','8\n'),
      [('Ordinary midpoint','midpoint(7,10)','8','An odd distance rounds toward the first value.'),
       ('Reverse rounding','midpoint(10,7)','9','Changing argument order can change the rounded side.'),
       ('Near maximum','midpoint(std::numeric_limits<int>::max()-2,std::numeric_limits<int>::max())','2147483646','Adding the endpoints would overflow.'),
       ('Across zero','midpoint(std::numeric_limits<int>::min(),std::numeric_limits<int>::max())','-1','Do not compute an overflowing sum.'),
       ('Unsigned type','midpoint(2u,8u)','5','Integral includes unsigned integers.')],
      ['std::integral is a C++20 concept checked during compilation.','std::midpoint handles endpoints without first adding them.'],
      'The requires clause excludes bool at compile time; std::midpoint performs overflow-safe arithmetic for accepted integer types. No runtime error handling is needed for an invalid type.',
      ['iostream','concepts','numeric','limits'])
    Q(14,'captured-threshold','Filter with a captured threshold','Functional',
      'Return a new vector of values strictly greater than threshold in input order. Do not change the source. Use std::copy_if with a lambda that captures the threshold by value.',
      'std::vector<int> above(const std::vector<int>& values,int threshold)',
      'std::vector<int> above(const std::vector<int>& values,int threshold){std::vector<int> result;std::copy_if(values.begin(),values.end(),std::back_inserter(result),[](int x){return x>0;});return result;}',
      'std::vector<int> above(const std::vector<int>& values,int threshold){std::vector<int> result;std::copy_if(values.begin(),values.end(),std::back_inserter(result),[threshold](int x){return x>threshold;});return result;}',
      'int main(){int threshold;if(!(std::cin>>threshold))return 2;std::vector<int> input;for(int x;std::cin>>x;)input.push_back(x);for(int v:above(input,threshold))std::cout<<v<<" ";std::cout<<"\\n";}',
      ('5 2 5 8 7\n','8 7 \n'),
      [('Strictly above','above({2,5,8,7},5)==std::vector<int>({8,7})','true','Equal does not count.'),
       ('Negative threshold','above({-4,-1,0},-2)==std::vector<int>({-1,0})','true','Compare with the supplied value, not zero.'),
       ('Empty input','above({},3).empty()','true','No input produces no output.'),
       ('Preserve input','([]{std::vector<int> v{1,9};auto r=above(v,4);return v==std::vector<int>({1,9})&&r==std::vector<int>({9});})()','true','Borrow the source as const.')],
      ['[threshold] copies that local value into the lambda.','back_inserter appends accepted values to result.'],
      'A lambda is a small callable written beside its use. Value capture makes the threshold available during each predicate call without modifying or borrowing the caller’s vector.',
      ['iostream','vector','algorithm','iterator'])
    Q(15,'erase-negative','Erase every negative element safely','Debug',
      'Change a vector in place so it keeps only nonnegative values, in the same order. Zero stays. All iterators used by this function must be obtained and used before an invalidating erase.',
      'void eraseNegative(std::vector<int>& values)',
      'void eraseNegative(std::vector<int>& values){auto p=std::find_if(values.begin(),values.end(),[](int n){return n<0;});if(p!=values.end())values.erase(p);}',
      'void eraseNegative(std::vector<int>& values){values.erase(std::remove_if(values.begin(),values.end(),[](int n){return n<0;}),values.end());}',
      'int main(){std::vector<int> v;for(int x;std::cin>>x;)v.push_back(x);eraseNegative(v);for(int x:v)std::cout<<x<<" ";std::cout<<"\\n";}',
      ('-2 0 4 -3 5\n','0 4 5 \n'),
      [('Several negatives','([]{std::vector<int> v{-2,0,4,-3,5};eraseNegative(v);return v==std::vector<int>({0,4,5});})()','true','Remove all matches, not just the first.'),
       ('All negatives','([]{std::vector<int> v{-1,-2};eraseNegative(v);return v.empty();})()','true','The new logical end may be begin().'),
       ('None negative','([]{std::vector<int> v{0,3};eraseNegative(v);return v==std::vector<int>({0,3});})()','true','Do not remove zero.'),
       ('Empty','([]{std::vector<int> v;eraseNegative(v);return v.empty();})()','true','The empty range is valid.')],
      ['remove_if rearranges retained elements and returns a new logical end.','erase removes the trailing elements from that end to values.end().'],
      'Vector erase invalidates iterators at and after the removed position. This erase-remove operation uses its iterator before erase changes the vector; it does not keep a stale iterator.',
      ['iostream','vector','algorithm'])
    Q(16,'frequency','Count records with an ordered map','Containers',
      'Return the number of times each input word appears. Use std::map so keys are ordered lexicographically when the caller iterates the result. Empty input gives an empty map. Case is significant.',
      'std::map<std::string,int> frequencies(const std::vector<std::string>& words)',
      'std::map<std::string,int> frequencies(const std::vector<std::string>& words){std::map<std::string,int> counts;for(const auto& w:words)counts[w]=1;return counts;}',
      'std::map<std::string,int> frequencies(const std::vector<std::string>& words){std::map<std::string,int> counts;for(const auto& w:words)++counts[w];return counts;}',
      'int main(){std::vector<std::string> words;for(std::string w;std::cin>>w;)words.push_back(w);for(const auto& [word,count]:frequencies(words))std::cout<<word<<":"<<count<<" ";std::cout<<"\\n";}',
      ('beta alpha beta\n','alpha:1 beta:2 \n'),
      [('Repeated key','frequencies({"b","a","b"}).at("b")','2','Increase the existing count.'),
       ('Ordered output','([]{auto m=frequencies({"z","a"});return m.begin()->first;})()','a','std::map orders keys.'),
       ('Case differs','([]{auto m=frequencies({"a","A"});return m.size()==2&&m.at("a")==1&&m.at("A")==1;})()','true','Do not fold case.'),
       ('Empty','frequencies({}).empty()','true','There are no counts to insert.')],
      ['operator[] creates a zero count for a missing key.','++ then increases either the new zero or a prior count.'],
      'A map stores key/value pairs and owns the strings. Its ordered iteration is useful for stable reports; an unordered_map may be faster when output order is irrelevant.',
      ['iostream','map','string','vector'])
    Q(17,'sort-unique','Sort before removing duplicate values','Algorithms',
      'Return each distinct integer exactly once in increasing order. Do not modify the input. std::unique removes adjacent duplicates only, so put the required operation before it.',
      'std::vector<int> sortedUnique(std::vector<int> values)',
      'std::vector<int> sortedUnique(std::vector<int> values){auto end=std::unique(values.begin(),values.end());values.erase(end,values.end());return values;}',
      'std::vector<int> sortedUnique(std::vector<int> values){std::sort(values.begin(),values.end());auto end=std::unique(values.begin(),values.end());values.erase(end,values.end());return values;}',
      'int main(){std::vector<int> values;for(int v;std::cin>>v;)values.push_back(v);for(int v:sortedUnique(values))std::cout<<v<<" ";std::cout<<"\\n";}',
      ('3 1 3 2 1\n','1 2 3 \n'),
      [('Nonadjacent repeats','sortedUnique({3,1,3,2,1})==std::vector<int>({1,2,3})','true','Sorting makes equal values adjacent.'),
       ('Already sorted','sortedUnique({-2,-2,0,4})==std::vector<int>({-2,0,4})','true','Retain one of each.'),
       ('Empty','sortedUnique({}).empty()','true','Algorithms accept empty ranges.'),
       ('One value','sortedUnique({7})==std::vector<int>({7})','true','Keep the sole value.')],
      ['sort puts equal integers next to one another.','unique returns a new logical end; erase shortens the vector.'],
      'The precondition for removing all duplicates with unique is that equal values are adjacent. Passing the vector by value copies it, so sorting does not rearrange the caller’s data.',
      ['iostream','vector','algorithm'])
    Q(18,'even-squares','Own the output of a lazy range pipeline','Ranges',
      'Read integers, keep even values, square them in order, and return an owning vector. Inputs and squares fit int. A view may borrow its source; do not return a view that refers to a local input.',
      'std::vector<int> evenSquares(const std::vector<int>& values)',
      'std::vector<int> evenSquares(const std::vector<int>& values){std::vector<int> result;for(int x:values)result.push_back(x*x);return result;}',
      'std::vector<int> evenSquares(const std::vector<int>& values){auto selected=values|std::views::filter([](int x){return x%2==0;})|std::views::transform([](int x){return x*x;});std::vector<int> result;for(int x:selected)result.push_back(x);return result;}',
      'int main(){std::vector<int> v;for(int x;std::cin>>x;)v.push_back(x);for(int x:evenSquares(v))std::cout<<x<<" ";std::cout<<"\\n";}',
      ('-2 3 4 5 0\n','4 16 0 \n'),
      [('Mixed','evenSquares({-2,3,4,5,0})==std::vector<int>({4,16,0})','true','Filter odd values before squaring.'),
       ('All odd','evenSquares({1,3,5}).empty()','true','No even item passes.'),
       ('Empty','evenSquares({}).empty()','true','An empty range yields an empty vector.'),
       ('Independent result','([]{std::vector<int> v{2};auto out=evenSquares(v);v[0]=9;return out==std::vector<int>({4});})()','true','Copy the selected values into owned storage.')],
      ['A filter view selects elements only when visited.','A transform view maps each selected value. Copy its results into a vector before returning.'],
      'A range view can borrow data and perform work lazily. The final vector owns its elements after this function returns, even when the caller later changes its input.',
      ['iostream','vector','ranges'])
    Q(19,'parse-count','Parse a bounded optional integer','Parsing',
      'Return an int for a complete decimal string in [0,1000]. Return std::nullopt for empty text, signs, trailing text, overflow, or out-of-range values. A string_view is length-bounded and is not assumed zero-terminated.',
      'std::optional<int> parseCount(std::string_view text)',
      'std::optional<int> parseCount(std::string_view text){int value=0;auto [end,error]=std::from_chars(text.data(),text.data()+text.size(),value);if(error!=std::errc{})return std::nullopt;return value;}',
      'std::optional<int> parseCount(std::string_view text){if(text.empty())return std::nullopt;int value=0;auto [end,error]=std::from_chars(text.data(),text.data()+text.size(),value);if(error!=std::errc{}||end!=text.data()+text.size()||value<0||value>1000)return std::nullopt;return value;}',
      'int main(){std::string word;std::getline(std::cin,word);auto n=parseCount(word);if(n)std::cout<<*n<<"\\n";else std::cout<<"invalid\\n";}',
      ('42\n','42\n'),
      [('Zero','parseCount("0")==std::optional<int>{0}','true','Zero is in range.'),
       ('Upper bound','parseCount("1000")==std::optional<int>{1000}','true','The maximum is inclusive.'),
       ('Beyond bound','!parseCount("1001")','true','Check value after parsing.'),
       ('Trailing characters','!parseCount("4x")','true','The whole view must be consumed.'),
       ('Negative rejected','!parseCount("-1")','true','Only nonnegative values are allowed.'),
       ('Empty and overflow','!parseCount("")&&!parseCount("9999999999999999999999")','true','A failed conversion has no value.')],
      ['from_chars gives an end pointer and an error code.','Require end == text.data()+text.size() and validate the numeric domain.'],
      'optional<int> represents either an owned integer or no valid result. The parser uses the view’s explicit end address, so it never reads beyond a nonterminated slice.',
      ['iostream','optional','string','string_view','charconv','system_error'])
    Q(20,'safe-path','Build a safe report path from one filename','Files',
      'Accept a single nonempty filename ending in .txt with no slash, backslash, or dot-dot name. Return root / filename as an optional path; reject a path or directory supplied as the filename. This is lexical validation for a trusted root, not a defense against symlinks in an untrusted directory.',
      'std::optional<std::filesystem::path> reportPath(const path& root,std::string_view filename)',
      'std::optional<std::filesystem::path> reportPath(const std::filesystem::path& root,std::string_view filename){return root/std::string(filename);}',
      'std::optional<std::filesystem::path> reportPath(const std::filesystem::path& root,std::string_view filename){if(filename.empty()||filename.find(\'/\')!=std::string_view::npos||filename.find(\'\\\\\')!=std::string_view::npos)return std::nullopt;std::filesystem::path leaf{std::string(filename)};if(leaf=="."||leaf==".."||leaf.filename()!=leaf||leaf.extension()!=".txt")return std::nullopt;return root/leaf;}',
      'int main(){std::string file;std::getline(std::cin,file);auto p=reportPath("reports",file);std::cout<<(p?p->generic_string():"invalid")<<"\\n";}',
      ('day.txt\n','reports/day.txt\n'),
      [('Valid leaf','reportPath("reports","day.txt")->generic_string()','reports/day.txt','Join the trusted root to the leaf name.'),
       ('Traversal rejected','!reportPath("reports","../secret.txt")','true','A path separator means it is not one filename.'),
       ('Absolute rejected','!reportPath("reports","/tmp/day.txt")','true','A filename cannot supply its own root.'),
       ('Wrong suffix','!reportPath("reports","day.csv")','true','Require the .txt extension.'),
       ('Backslash rejected','!reportPath("reports","..\\\\day.txt")','true','Check both common separator characters.'),
       ('Empty rejected','!reportPath("reports","")','true','A missing name is invalid.')],
      ['Validate the filename text before joining it.','path.extension() examines the suffix of the one remaining leaf.'],
      'filesystem::path joins path parts without hand-written separators. Lexical validation is suitable when the root directory itself is trusted; secure access to an untrusted tree needs OS-level checks.',
      ['iostream','filesystem','optional','string','string_view'])
    Q(21,'transaction-report','Load an entire report or preserve the old one','Integration',
      'Report::load reads zero or more id|quantity lines. Id must be positive and unique; quantity must be 0..1000; at most 100 lines. Numbers must be complete decimal integers. On any invalid line or input I/O error return false and keep every old record. On success replace all records, including with an empty report. total() returns long long. No concurrent callers.',
      'class Report: bool load(std::istream&), size_t size() const, long long total() const',
      'struct Row{int id,quantity;};class Report{std::vector<Row> rows_;public:bool load(std::istream& in){std::string line;while(std::getline(in,line)){auto p=line.find(\'|\');if(p==std::string::npos)return false;int id=std::stoi(line.substr(0,p)),qty=std::stoi(line.substr(p+1));rows_.push_back({id,qty});}return true;}std::size_t size()const{return rows_.size();}long long total()const{long long n=0;for(const auto& r:rows_)n+=r.quantity;return n;}};',
      'struct Row{int id,quantity;};class Report{std::vector<Row> rows_;public:bool load(std::istream& in){std::vector<Row> next;std::set<int> ids;std::string line;while(std::getline(in,line)){auto p=line.find(\'|\');if(p==std::string::npos||line.find(\'|\',p+1)!=std::string::npos)return false;int id=0,qty=0;auto left=std::string_view(line).substr(0,p),right=std::string_view(line).substr(p+1);if(left.empty()||right.empty())return false;auto [a,ae]=std::from_chars(left.data(),left.data()+left.size(),id);auto [b,be]=std::from_chars(right.data(),right.data()+right.size(),qty);if(ae!=std::errc{}||be!=std::errc{}||a!=left.data()+left.size()||b!=right.data()+right.size()||id<=0||qty<0||qty>1000||next.size()>=100||!ids.insert(id).second)return false;next.push_back({id,qty});}if(in.bad())return false;rows_.swap(next);return true;}std::size_t size()const{return rows_.size();}long long total()const{long long n=0;for(const auto& r:rows_)n+=r.quantity;return n;}};',
      'int main(){Report report;std::ostringstream text;std::string line;while(std::getline(std::cin,line))text<<line<<"\\n";std::istringstream input(text.str());std::cout<<std::boolalpha<<report.load(input)<<" "<<report.size()<<" "<<report.total()<<"\\n";}',
      ('1|20\n2|5\n','true 2 25\n'),
      [('Valid rows','([]{Report r;std::istringstream in("1|20\\n2|5\\n");return r.load(in)&&r.size()==2&&r.total()==25;})()','true','Collect accepted rows before publishing.'),
       ('Invalid replacement rolls back','([]{Report r;std::istringstream a("1|5\\n"),b("2|7\\n2|8\\n");r.load(a);return !r.load(b)&&r.size()==1&&r.total()==5;})()','true','A duplicate must leave old rows unchanged.'),
       ('Quantity bound','([]{Report r;std::istringstream a("1|1001\\n");return !r.load(a)&&r.size()==0;})()','true','Reject before appending.'),
       ('Strict integer','([]{Report r;std::istringstream a("1|4junk\\n");return !r.load(a)&&r.size()==0;})()','true','Require complete conversion.'),
       ('Empty replacement','([]{Report r;std::istringstream a("1|9\\n"),b("");r.load(a);return r.load(b)&&r.size()==0&&r.total()==0;})()','true','An empty valid input is a successful replacement.'),
       ('Hundred-row limit','([]{Report r;std::ostringstream t;for(int i=1;i<=101;++i)t<<i<<"|1\\n";std::istringstream in(t.str());return !r.load(in)&&r.size()==0;})()','true','Reject row 101 without publishing partial data.')],
      ['Parse into a local vector and set of ids.','Swap the accepted vector with the old one only after the entire input succeeds.'],
      'The local candidate owns records until the last check. Its swap is the single publication point: failed parse leaves the old report intact, while a valid empty input clears it.',
      ['iostream','vector','set','string','string_view','sstream','charconv','system_error','cstddef'])
