import {sourceData,sourceCoding} from './read-source.mjs';
import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {chooseBook} from './book_test_helpers.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),catalog=sourceCoding();
let opts={headless:true};if(process.env.CHROMIUM_MODULE){const {default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));opts={...opts,args:['--no-sandbox','--disable-gpu','--disable-webgl','--disable-dev-shm-usage'],executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
const browser=await chromium.launch(opts),p=await browser.newPage({viewport:{width:1512,height:1100},reducedMotion:'reduce'}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));
const waitDone=()=>p.waitForFunction(()=>!document.querySelector('[data-action="lab-test"]').disabled,{},{timeout:80000});
try{
 await p.route('https://**',route=>route.abort());await p.goto(process.env.STUDIO_URL||pathToFileURL(path.join(root,'dist-offline/index.html')).href);await chooseBook(p,'cpp-book-02');await p.locator('[data-mode="coding"]').click();await p.waitForSelector('#lab-question');
 assert.equal(await p.locator('#lab-question optgroup[label="Practice questions"] option').count(),24);assert.equal(await p.locator('#lab-question option[value^="worked-B02-"]').count(),78);results.push('Book II has 24 questions and 78 source-linked workshops, grouped by chapter.');
 const original=catalog.workedPrograms.find(w=>w.sourceId==='B02-L0002'),report=catalog.workedPrograms.find(w=>w.sourceId==='B02-L0106');
 const modified=original.source.replace('b{7}','b{8}');assert.notEqual(modified,original.source);
 const file=path.join(root,'coding_lab/build/book-two-browser-mutation.cpp'),exe=file.slice(0,-4);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,modified);
 const compiled=spawnSync('g++',['-std=c++20','-pthread',file,'-o',exe],{encoding:'utf8',timeout:30000});assert.equal(compiled.status,0,compiled.stderr);const changed=spawnSync(exe,[],{encoding:'utf8',timeout:5000});assert.equal(changed.status,0);assert.equal(changed.stdout,'false\n');
 const observedInputs=[];let simulated=0;await p.route('https://godbolt.org/api/**',async route=>{
  const body=route.request().postDataJSON(),source=body.source.replace(/^#line 1 "main.cpp"\n/,'').trimEnd(),stdin=body.options.executeParameters.stdin;
  let check;if(source===original.source.trimEnd())check=original.checks[0];else if(source===modified.trimEnd())check={...original.checks[0],stdout:changed.stdout};else if(source===report.source.trimEnd()){check=report.checks.find(c=>c.input===stdin);observedInputs.push(stdin);}else{await route.abort();return;}
  assert.ok(check,'Unexpected input');simulated++;
  const lines=s=>s.replace(/\n+$/,'').split('\n').map(text=>({text}));await route.fulfill({json:{code:check.exitCode,didExecute:true,stdout:lines(check.stdout),stderr:check.stderr?lines(check.stderr):[],buildResult:{code:0,stderr:[]}}});
 });
 await p.selectOption('#lab-question',original.id);assert.equal(await p.locator('#lab-editor').inputValue(),original.source);await p.locator('[data-action="lab-test"]').click();await waitDone();assert.equal(await p.locator('.lab-case.passed').count(),1);results.push('The original Book II strong-value program passes its recorded behavior check.');
 await p.fill('#lab-editor',modified);await p.locator('[data-action="lab-test"]').click();await waitDone();assert.equal(await p.locator('.lab-case.failed').count(),1);assert.ok((await p.locator('.lab-case.failed').textContent()).includes('false'));results.push('A locally compiled mutation produces failed feedback and actual output.');
 await p.screenshot({path:path.join(root,'docs/preview-book-two-feedback.png')});
 await p.selectOption('#lab-question',report.id);assert.ok((await p.locator('.lab-adaptation').textContent()).includes('book header'));await p.locator('[data-action="lab-test"]').click();await waitDone();assert.equal(await p.locator('.lab-case.passed').count(),3);assert.deepEqual(observedInputs,report.checks.map(x=>x.input));results.push('The joined Book II report passes valid, invalid-priority, and duplicate-id cases including stderr and exit codes.');
 await p.reload();assert.equal(await p.locator('#lab-question').inputValue(),report.id);await p.locator('[data-action="lab-original-listing"]').click();assert.equal(await p.locator('#series-code-select').inputValue(),'B02-L0106');await p.selectOption('#series-code-select','B02-L0104');await p.locator('[data-action="series-edit-in-lab"]').click();assert.equal(await p.locator('#lab-question').inputValue(),report.id);results.push('Saved selection and exact header/implementation/source navigation survive reload.');
 await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.lab-header').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(root,'docs/preview-book-two-mobile.png')});results.push('390px mobile layout has no horizontal overflow.');
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/book-two-browser-results.json'),JSON.stringify({date:new Date().toISOString(),liveExternalRequests:0,simulatedFromLocalFixtures:simulated,results,errors},null,2)+'\n');console.log(results.join('\n'));
}finally{await browser.close();}
