import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import {chooseBook,currentBook} from './book_test_helpers.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),content=JSON.parse(await fs.readFile(path.join(root,'src/content.json'),'utf8'));
let options={headless:true};if(process.env.CHROMIUM_MODULE){const{default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));options={...options,args:ch.args,executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
const browser=await chromium.launch(options),p=await browser.newPage({viewport:{width:1512,height:1100},reducedMotion:'reduce'}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(pathToFileURL(path.join(root,'dist/index.html')).href);assert.equal(await p.locator('.book-chapter-dropdown').count(),10);assert.equal(await p.locator('#course-select').count(),0);
for(const c of content.courses.filter(c=>c.kind==='textbook')){
 const menu=p.locator(`.book-chapter-dropdown[data-course="${c.id}"]`),options=await menu.locator('option').allTextContents();assert.equal(options.length,c.chapters.length+2+(c.glossary?.length?1:0));assert.ok((await menu.getAttribute('aria-label')).startsWith(c.title));
 for(const ch of [c.chapters.find(ch=>ch.number===1),c.chapters.at(-1)]){
  await menu.selectOption(String(ch.number));assert.equal(await currentBook(p),c.id);assert.equal(await p.locator('#chapter-select').inputValue(),String(ch.number));assert.equal(await p.locator('.lesson-heading').textContent(),ch.title);assert.equal(await p.locator('.book-menu.active').getAttribute('data-course'),c.id);
 }
 await menu.selectOption('1');await p.fill('#personal-note',`Notes stay with ${c.id}`);await p.locator('[data-action="reviewed"]').click();
 if(c.glossary?.length){await menu.selectOption('-1');assert.equal(await p.locator('#glossary-search').count(),1);}
}
results.push('Ten independent labeled chapter dropdowns; all book boundaries, final chapters, glossary choices, notes and review actions work');
for(const c of content.courses.filter(c=>c.kind==='textbook')){await chooseBook(p,c.id);await p.locator(`.book-chapter-dropdown[data-course="${c.id}"]`).selectOption('1');assert.equal(await p.locator('#personal-note').inputValue(),`Notes stay with ${c.id}`);}
await p.reload();assert.equal(await currentBook(p),'cpp-book-08');assert.equal(await p.locator('#personal-note').inputValue(),'Notes stay with cpp-book-08');results.push('Independent notes and selected book survive switching and reload');
await p.locator('#book-dropdowns').evaluate(el=>el.scrollTop=0);await p.screenshot({path:path.join(root,'docs/preview-independent-book-dropdowns.png')});await p.locator('#book-dropdowns').evaluate(el=>el.scrollTop=el.scrollHeight);await p.screenshot({path:path.join(root,'docs/preview-independent-book-dropdowns-last.png')});
await p.setViewportSize({width:390,height:844});await p.locator('[data-action="open-menu"]').click();await p.locator('#book-dropdowns').evaluate(el=>el.scrollTop=0);await p.screenshot({path:path.join(root,'docs/preview-independent-book-dropdowns-mobile.png')});await p.locator('.book-chapter-dropdown[data-course="cpp-book-03"]').selectOption('2');assert.equal(await currentBook(p),'cpp-book-03');assert.equal(await p.locator('#chapter-select').inputValue(),'2');assert.equal(await p.locator('#sidebar').evaluate(el=>el.classList.contains('open')),false);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));results.push('Mobile book selection opens the chosen chapter and closes the drawer without page overflow');
await p.locator('[data-action="open-menu"]').click();await p.locator('[data-action="personal-material"]').click();assert.equal(await currentBook(p),'my-material');assert.ok((await p.locator('#workspace').textContent()).includes('Make this space yours'));results.push('Personal material remains available separately');
assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/book-dropdown-browser-results.json'),JSON.stringify({results,errors},null,2));console.log(results.join('\n'));await browser.close();
