#!/usr/bin/env python3
"""Eight original teaching views grounded in the supplied Chapter 1 examples."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def build(data):
 specs=[
 dict(book=1,listing=3,title='Sort readings without losing each reading’s value',kind='activity',nodes=[
  ('readings','Own three readings',['std::vector<Reading> r{{3, 18.2}, {1, 20.1}, {2, 19.4}};','// Each element keeps its id and value together.']),
  ('compare','Compare identifiers',['return a.id < b.id;','// The comparator chooses the ordering.']),
  ('sort','Reorder the vector',['std::sort(r.begin(), r.end(),','    [](const Reading& a, const Reading& b){','        return a.id < b.id;','    });','// Same call, formatted across lines.']),
  ('print','Visit the ordered values',["for (const auto& x : r)","    std::cout << x.id << ':' << x.value << '\\n';",'// Read each element without copying it.'])],edges=[('readings','sort','flow','input order: 3, 1, 2'),('compare','sort','dependency','comparison rule supplied to sort'),('sort','print','flow','output order: 1, 2, 3')],legend='Solid arrows show execution and data order. The dashed arrow shows a dependency on the comparison rule; it is not inheritance or ownership.',focus=[
  (4,6,'Keep related data together',['struct defines a value type named Reading. Each value contains an integer id and a double value.','main is the program’s entry point. The opening brace begins its body.','vector owns its Reading elements. The nested braces construct three complete readings, so sorting moves each id and value together.'],'A Reading is one record. The vector owns a collection of these records.','The records are created before sorting.','Separate arrays for ids and values would need perfectly matched swaps. One value type keeps related fields together.','Each id remains attached to its original measurement. The vector stays alive during sorting and printing.','Sorting ids alone would detach them from the matching values.'),
  (7,8,'Order, then borrow each result',['sort receives an iterator pair marking a half-open range. The lambda, a small unnamed function, takes const references: it borrows two records without changing them and returns whether the first id is smaller.','The colon in this range-based for means “take each element from r.” auto lets the compiler find Reading; const & borrows it for read-only access. << inserts values into the output stream.'],'The algorithm changes the order of values; the loop observes the resulting order.','Both lines run after construction and before the vector is destroyed at the end of main.','The comparator states one rule that the library sorting algorithm can apply repeatedly.','The comparator must provide a strict weak ordering. Using < on these integer ids satisfies that rule.','Using <= breaks the ordering contract. Keeping a reference after the vector dies would leave a dangling reference.')]),
 dict(book=2,listing=2,title='Give an identifier its own value type',kind='class',nodes=[
  ('type','UserId',['struct UserId{ int value; };','// A wrapper type with one public field.']),
  ('equal','Equality operation',['bool operator==(UserId a, UserId b){','    return a.value==b.value;','}','// Parameters are small value copies.']),
  ('caller','Caller',['UserId a{7}, b{7};',"std::cout << std::boolalpha << (a==b) << '\\n';",'// The stream prints true, then a newline.'])],edges=[('caller','type','dependency','constructs two UserId values'),('caller','equal','dependency','uses overloaded equality'),('equal','type','dependency','accepts UserId parameters')],legend='Dashed arrows show compile-time dependencies on a type or function. There is no inheritance and no heap ownership in this example.',focus=[
  (2,3,'State what equality means',['struct creates the UserId type. Its value member is public by default. The semicolon ends the type declaration.','operator== defines equality for two UserId values. The parameters are copies; comparing their integer fields produces a bool result.'],'The wrapper gives a name and type to the meaning “user identifier.”','The declarations appear before the call in main, so the compiler can resolve a==b.','The type makes intent visible. For a small identifier, copying is simpler than managing pointers.','Two identifiers with the same value compare equal. Equality must be consistent wherever the type is used.','Comparing addresses would compare objects’ locations rather than identifier values. A public field allows arbitrary integers, so this type alone does not enforce valid user ranges.'),
  (4,4,'Call the type’s equality operation',['Braces initialize two separate UserId objects with the value 7. a==b calls the overload. std::boolalpha makes the stream print true instead of 1, followed by a newline.'],'The caller observes equality without depending on the comparison’s spelling.','This is the entry point and the complete output-producing call.','A named type helps separate user identifiers from unrelated integers in larger interfaces.','Both objects live until main returns; no reference escapes. The expected output is true.','Changing operator== to compare another property changes every caller’s meaning of equality.')]),
 dict(book=3,listing=3,title='Carry one invariant through a linear scan',kind='activity',nodes=[
  ('first','Initialize from the first item',['int best=v.at(0);','// Empty input throws std::out_of_range.']),
  ('test','Visit each remaining index',['for(std::size_t i=1;i<v.size();++i)','// i never reaches the index v.size().']),
  ('update','Replace only with a larger value',['if(v[i]>best) best=v[i];','// best is the largest item seen so far.']),
  ('return','Return the result',['return best;','// For 4, 9, 2, 7 the result is 9.'])],edges=[('first','test','flow','begin at index 1'),('test','update','flow','another element exists'),('update','test','flow','advance and test again'),('test','return','flow','all elements visited')],legend='Solid arrows describe activity flow, including the loop back to its condition. They do not describe class inheritance.',focus=[
  (3,3,'Maintain the largest-so-far rule',['const vector<int>& v borrows the caller’s vector without modifying it. at(0) checks the first index. The loop starts at 1, uses < to stop before size(), increments i, and replaces best only when the next value is larger. return sends the answer back.'],'After each completed iteration, best is the maximum of the values visited so far.','The function is defined before main calls it. The scan itself runs at execution time.','One pass is enough; sorting would do extra work and change the input order.','The input must be nonempty for a successful result. best must be a value from the visited prefix.','Starting best at zero gives a wrong result for all-negative input. Replacing < with <= reads beyond the vector at the last iteration.'),
  (4,4,'Check the example trace',['The brace list constructs a temporary vector from 4, 9, 2, 7. It stays alive through this call, so the borrowed const reference is valid. The returned integer is sent to cout, then a newline.'],'The trace is best=4, then 9, then 9, then 9.','The temporary input is destroyed after the full expression finishes.','This small fixture makes the scan’s invariant easy to check before using larger inputs.','The final output is 9. The function returns an integer value, not a reference to a temporary.','Returning a reference to a local best would produce a dangling reference once the function returns.')]),
 dict(book=4,listing=3,title='Trace a value across a function boundary',kind='activity',nodes=[
  ('call','Caller supplies a value',['transform(7)','// The integer is converted to uint64_t.']),
  ('body','Compute in the function',['return (x + 5) * 4;','// Parentheses make addition happen first.']),
  ('output','Observe the result',['std::cout << transform(7) << "\\n";','// The expression yields 48.'])],edges=[('call','body','flow','x receives 7'),('body','output','flow','return the value 48')],legend='Arrows show value and execution flow. This is a source-level trace, not a claim about a particular CPU instruction sequence.',focus=[
  (4,6,'Separate the interface from the expression',['std::uint64_t is an unsigned integer type with exactly 64 value bits on platforms that provide it. The parameter x is a value copy.','Parentheses compute x+5 first; multiplication then produces the result. return passes that value to the caller.','The closing brace ends the function body.'],'The function maps one unsigned input value to one unsigned output value.','Its declaration and body are visible to the compiler before main.','A named function provides one place to inspect and change this arithmetic rule.','For the fixture 7, the intermediate is 12 and the result is 48. Unsigned arithmetic wraps modulo 2^64 if its range is exceeded.','Assuming these are unbounded mathematical integers gives wrong results for large inputs. The source alone does not promise one particular machine instruction sequence.'),
  (8,10,'Observe rather than assume',['main begins the program’s entry-point body.','The nested call completes before its result is inserted into cout. The string adds a newline.','The closing brace ends main; falling off the end is equivalent to returning zero.'],'Output exposes a result that can be checked in a test.','This is the runtime caller of transform.','A tiny input and exact output help debug arithmetic before inspecting generated instructions.','For this fixture the output is 48 followed by a newline.','A different integer width or changed operator order may change results; keep tests near the rule.')]),
 dict(book=5,listing=3,title='Compile separate files against one declaration',kind='component',nodes=[
  ('header','Public header',['// include/calc/add.hpp','int add(int a, int b);','// Declaration: the call signature.']),
  ('impl','Implementation',['// src/add.cpp','#include "calc/add.hpp"','int add(int a, int b) { return a + b; }']),
  ('main','Application',['// app/main.cpp','#include "calc/add.hpp"','add(20, 22)','// The caller uses the public declaration.']),
  ('link','Linked program',['// Link both compiled .cpp files.','// The call resolves to one definition.','// Running the program prints 42.'])],edges=[('impl','header','dependency','includes declaration'),('main','header','dependency','includes declaration'),('impl','link','flow','compiled definition'),('main','link','flow','compiled caller')],legend='Dashed arrows are include dependencies. Solid arrows describe build inputs flowing into the linker. The boxes describe source files and a build result, not C++ inheritance.',focus=[
  (1,3,'Declare the interface',['This comment names the first file in the book’s combined listing. The packaged project contains that separate file.','#pragma once is a widely supported header guard directive; it asks the compiler to include this header once per translation unit.','The semicolon makes this a function declaration, with no body. It tells callers the parameter and result types.'],'The header is the shared promise that a function named add accepts two ints and returns an int.','Both .cpp files include this header during preprocessing.','One public declaration prevents callers from inventing incompatible signatures.','The definition must match this declaration. The project must supply exactly one external definition.','A header alone does not provide executable code for the function; omitting the implementation from linking leaves an unresolved symbol.'),
  (5,7,'Supply the definition',['This comment names the implementation file.','The include makes the public declaration visible to this translation unit.','The body defines add and returns the sum of its value parameters.'],'The implementation supplies the code behind the declared interface.','The compiler processes this .cpp separately; the linker later joins it with the caller.','A private implementation can change while callers keep using the same interface.','The fixture 20+22 fits in int and produces 42. In general, signed overflow must be avoided.','Copying the same non-inline definition into several .cpp files violates the one-definition rule.')]),
 dict(book=6,listing=1,title='Split independent writes, then join before reading',kind='ownership / activity',nodes=[
  ('owner','main owns both arrays',['std::array<int,6> input{1,2,3,4,5,6}, squared{};','// Storage remains alive until both tasks finish.']),
  ('left','First task: indices 0, 1, 2',['auto first=std::async(std::launch::async,transform,0,3);','// This task writes only its own slice.']),
  ('right','Second task: indices 3, 4, 5',['auto second=std::async(std::launch::async,transform,3,6);','// Its slice does not overlap the first.']),
  ('join','Wait, then reduce',['first.get(); second.get();','std::accumulate(squared.begin(),squared.end(),0)','// Reduction reads only after both tasks complete.'])],edges=[('owner','left','dependency','borrow arrays through the lambda'),('owner','right','dependency','borrow the same live storage'),('left','join','flow','first.get() completes'),('right','join','flow','second.get() completes')],legend='Dashed arrows show borrowed access, not transfer of ownership. Solid arrows show completion dependencies before the final read. The tasks may overlap in time; the diagram does not promise which runs first.',focus=[
  (7,10,'Share access without sharing write locations',['array stores six integers in each value. input gets 1 through 6; squared{} initializes its six integers to zero.','The lambda captures surrounding variables by reference with [&]. begin and end are value parameters naming a half-open slice.','The loop writes squared[i] from input[i]. Different tasks receive nonoverlapping index ranges.','The brace and semicolon finish the lambda object definition.'],'Both tasks use the same arrays but write different integer objects within squared.','The arrays live in main, outside the asynchronous tasks.','Independent slices let the work run concurrently without a mutex for these separate elements.','The arrays must outlive all task access, indices must be in range, and no two tasks may write the same element.','Overlapping slices introduce a data race. Capturing references to destroyed local arrays would access invalid storage.'),
  (11,13,'Establish completion before observation',['std::launch::async requires asynchronous execution. The first future represents the task for [0,3).','The second task handles [3,6), so every index is assigned exactly once.','get waits for each task’s result and rethrows a task exception if one occurred. Only after both calls does main read the output array.'],'A future is a handle through which the caller waits for a task’s result or exception.','These lines sit between constructing the lambda and printing/reducing squared.','Completion synchronization makes the finished writes visible before the later reads.','The reduction begins after both get calls. The squares are 1, 4, 9, 16, 25, 36 and their sum is 91.','Reading squared before completion can race with task writes. This CPU example neither launches a CUDA kernel nor proves a speedup.')]),
 dict(book=7,listing=2,title='Reject bad work before changing the queue',kind='activity',nodes=[
  ('queue','Initial queue',['std::vector<int> jobs{4};','constexpr std::size_t capacity=2;','// One slot is initially used.']),
  ('guard','Check value and capacity',['if(x<0||x>100||jobs.size()==capacity)','    return false;','// Failure leaves the vector unchanged.']),
  ('append','Commit accepted work',['jobs.push_back(x);','return true;','// Mutation follows the admission check.']),
  ('check','Check the final state',['if(jobs!=std::vector<int>{4,7})return 1;','// 101 is invalid; 8 is rejected as full.'])],edges=[('queue','guard','flow','calls with 7, 101, 8'),('guard','append','flow','only when all guards pass'),('append','check','flow','after all three calls'),('guard','check','flow','rejected calls do not append')],legend='Solid arrows show conditional execution and the final check. Each submit call returns before the next call begins; this example has no concurrent producer.',focus=[
  (6,7,'Check first, mutate second',['The queue starts with 4. constexpr makes capacity a compile-time constant equal to two.','[&] borrows jobs and capacity. || means logical OR; if any guard is true, return false ends the call. Only a passing call reaches push_back and returns true.'],'Admission is a boundary: reject inputs outside 0–100 and requests that would exceed capacity.','The lambda runs three times from the next source line.','Keeping checks before mutation makes rejection easy to reason about and test.','At this boundary, jobs.size() never exceeds two and a rejected call preserves its previous state.','Pushing first and checking later would briefly or permanently violate capacity. Concurrent callers would need synchronization; this code is a single-thread model.'),
  (8,10,'Test results and state together',['The calls run in order: 7 is accepted, 101 is invalid, and 8 finds the queue full.','The explicit comparison returns failure status 1 unless the vector is exactly {4,7}.','boolalpha prints true/false. The observed results are accepted=true, invalid=false, full=false, count=2.'],'The test checks both returned decisions and the state those decisions leave behind.','The fixture is inside main, after all three submissions.','A boolean alone could hide an unwanted state change; checking the vector catches it.','Only one additional job is stored. Invalid and full calls leave it unchanged.','Calling false an error category loses the distinction between invalid input and temporary saturation; Book VIII’s outcome type addresses that need.')]),
 dict(book=8,listing=1,title='Distinguish invalid requests from temporary saturation',kind='state / activity',nodes=[
  ('count','Service model state',['unsigned queued=0;','// queued is 0, 1, or 2.']),
  ('invalid','Invalid input branch',['if(n<0||n>100)return Outcome::invalid;','// No state change; caller should fix input.']),
  ('busy','Saturated branch',['if(queued==2)return Outcome::busy;','// No state change; capacity is exhausted.']),
  ('accepted','Accepted transition',['++queued;','return Outcome::accepted;','// State changes 0 to 1 or 1 to 2.'])],edges=[('count','invalid','flow','check input first'),('invalid','busy','flow','continue only when input is valid'),('busy','accepted','flow','continue only when queued < 2'),('accepted','count','flow','next request observes new count')],legend='Solid arrows show the order of guards and permitted accepted transitions. An invalid or busy return ends that call without changing queued. This is a bounded state model, not a running network service.',focus=[
  (6,7,'Return an explicit outcome',['enum class declares a scoped set of named outcomes. Callers use names such as Outcome::busy. queued is an unsigned count initialized to zero.','[&] borrows queued. The invalid guard has priority, then the full guard. Only acceptance increments the count. Each return ends the current submit call.'],'An outcome value says why a request was or was not admitted.','This lambda is the admission boundary of the toy service model.','Callers can respond differently to invalid work and temporary lack of space without inspecting internal state.','The count remains in 0–2. Rejected requests do not change it. Invalid input is reported as invalid even when capacity is full.','Treating busy as accepted would mislead callers. Concurrent access would race without synchronization, and a real queue would also need completion/removal behavior.'),
  (8,9,'Make outcomes observable',['The capture-free lambda maps an Outcome to a string_view of a string literal. The trailing -> states the result type; the ?: operators choose the text. String literals live for the program’s lifetime.','The colon introduces a range-based loop. n is a value copy of each array element: 2, -1, 3, 4. Submit and format each outcome, then print a newline.'],'The fixture prints accepted, invalid, accepted, busy on four lines.','Formatting happens after each call returns its typed outcome.','Readable results allow tests and callers to distinguish rejection reasons.','The string_view must refer to live text; here it refers to string literals. The count ends at two.','Returning a string_view of a temporary string would dangle. Adding a new enum value requires reviewing the formatter, whose last branch currently treats any remaining value as busy.')])]
 for s in specs:
  c=next(c for c in data['courses'] if c.get('series',{}).get('number')==s['book']);e=next(e for e in c['series']['listings'] if e['id']==f'B{s["book"]:02}-L{s["listing"]:04}');source=(ROOT/e['filename']).read_text();lines=source.splitlines();focus=[]
  for start,end,title,explain,what,where,why,invariant,risk in s['focus']:
   assert len(explain)==end-start+1
   focus.append(dict(title=title,file=e['filename'],lineStart=start,lineEnd=end,code='\n'.join(lines[start-1:end]),explain=explain,what=what,where=where,why=why,invariant=invariant,risk=risk))
  d=dict(source=e['filename'],listingId=e['id'],overview=dict(title=s['title'],kind=s['kind'],nodes=[dict(id=i,label=l,code=code) for i,l,code in s['nodes']],edges=[dict(zip(['from','to','kind','label'],row)) for row in s['edges']],explanation=s['legend']),extra_overviews=[],focus=focus)
  c['diagrams']['1']=d
  (ROOT/f'diagrams/cpp_book{s["book"]:02}.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
 return data
if __name__=='__main__':
 p=ROOT/'src/content.json';p.write_text(json.dumps(build(json.loads(p.read_text())),ensure_ascii=False,indent=2))
