import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFile(path.join(root,p),'utf8');
const [template,app,data,styles,css,teaching,series]=await Promise.all(['src/index.html','src/app.js','src/content.json','src/styles.css','vendor/tailwind.css','src/teaching.js','src/series.js'].map(read));
JSON.parse(data);
const safe=x=>x.replace(/<\/script/gi,'<\\/script');
const html=template.replace('/*__TAILWIND__*/',()=>css).replace('/*__CUSTOM_CSS__*/',()=>styles).replace('/*__CONTENT__*/',()=>safe(data)).replace('/*__APP_JS__*/',()=>safe(app.replace('/*__TEACHING_JS__*/',()=>teaching).replace('/*__SERIES_JS__*/',()=>series)));
await fs.mkdir(path.join(root,'dist'),{recursive:true});
await fs.writeFile(path.join(root,'dist/index.html'),html);
console.log(`Built offline app: ${Math.round(Buffer.byteLength(html)/1024)} KB`);
