import {sourceData,sourceCoding} from './read-source.mjs';
if(process.env.STUDY_STUDIO_ALLOW_EXTERNAL_COMPILATION!=='1'){console.error('External compiler test disabled. This test submits the current Book I source code and sample input to Compiler Explorer. Obtain the source owner’s approval before opting in.');process.exit(2);}
import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import {chooseBook,currentBook} from './book_test_helpers.mjs';
import {labBuildProgram,labRequest} from '../src/coding-core.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),catalog=sourceCoding().questions;
let options={headless:true};if(process.env.CHROMIUM_MODULE){const{default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));options={...options,args:ch.args,executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
if(process.env.HTTPS_PROXY)options.proxy={server:process.env.HTTPS_PROXY};
const browser=await chromium.launch(options),p=await browser.newPage({viewport:{width:1512,height:1100},reducedMotion:'reduce',ignoreHTTPSErrors:!!process.env.HTTPS_PROXY}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>{if(r.url().includes('godbolt.org'))console.log('Compiler request failed:',r.failure()?.errorText);});
try{
 await p.goto(process.env.STUDIO_URL||pathToFileURL(path.join(root,'dist-offline/index.html')).href);assert.equal(await p.locator('.book-chapter-dropdown').count(),10);
 await p.locator('[data-mode="coding"]').click();await p.locator('#lab-editor').waitFor();assert.ok((await p.locator('#lab-question').textContent()).includes('strategy')||(await p.locator('#lab-question').textContent()).includes('policy'));
 await p.screenshot({path:path.join(root,'docs/preview-coding-lab.png'),fullPage:true});
 for(const course of [...new Set(catalog.map(q=>q.courseId))]){
  await chooseBook(p,course);await p.locator('[data-mode="coding"]').click();assert.equal(await p.locator('#lab-question optgroup[label="Practice questions"] option').count(),catalog.filter(q=>q.courseId===course).length);
  await p.fill('#lab-editor','// saved '+course+'\n'+catalog.find(q=>q.courseId===course).starter);
 }
 for(const course of [...new Set(catalog.map(q=>q.courseId))]){await chooseBook(p,course);assert.ok((await p.locator('#lab-editor').inputValue()).startsWith('// saved '+course));}
 results.push('All ten books expose every question in their current catalogs; drafts remain independent across book switches.');
 await chooseBook(p,'cpp-book-01');await p.selectOption('#lab-question','b1-add');await p.fill('#lab-editor',catalog.find(q=>q.id==='b1-add').solution);await p.fill('#lab-stdin','10 -4\n');
 const requests=[];p.on('request',r=>{if(r.url().includes('godbolt.org/api/'))requests.push(r.url());});
 await p.locator('[data-action="lab-run"]').click();await p.waitForFunction(()=>!document.querySelector('[data-action="lab-run"]').disabled,{},{timeout:80000});
 const liveText=await p.locator('#lab-results').textContent();await fs.writeFile(path.join(root,'tests/coding-live-browser-output.txt'),liveText);
 assert.ok(liveText.includes('Run finished successfully.'),'Actual browser API run failed: '+liveText);assert.equal((await p.locator('.lab-stdout').textContent()).trim(),'6');
 console.log('Live API check completed.');results.push('LIVE Compiler Explorer GCC 14.2 run from the standalone file: input 10 -4 produced 6.');
 await p.locator('[data-action="lab-test"]').click();await p.waitForFunction(()=>!document.querySelector('[data-action="lab-test"]').disabled,{},{timeout:80000});assert.equal(await p.locator('.lab-case.passed').count(),4);console.log('Live API check completed.');results.push('LIVE reference solution: four checks passed.');
 await p.fill('#lab-editor',catalog.find(q=>q.id==='b1-add').starter);assert.ok((await p.locator('.lab-run-status').textContent()).includes('Edited since'));await p.fill('#lab-command','test');await p.locator('#lab-command-form button').click();await p.waitForFunction(()=>!document.querySelector('[data-action="lab-test"]').disabled,{},{timeout:80000});assert.equal(await p.locator('.lab-case.failed').count(),3);assert.ok((await p.locator('.lab-case.failed').first().textContent()).includes('Use both parameters'));console.log('Live API check completed.');results.push('LIVE incorrect implementation: three failures explain expected and actual values; terminal test command works.');
 await p.screenshot({path:path.join(root,'docs/preview-coding-failed-checks.png'),fullPage:true});
 await p.fill('#lab-editor','#include <iostream>\nint add(int a, int b) { return a + b }\n');await p.locator('[data-action="lab-run"]').click();await p.waitForFunction(()=>!document.querySelector('[data-action="lab-run"]').disabled,{},{timeout:80000});assert.ok((await p.locator('#lab-results').textContent()).includes('Build failed'));assert.ok(await p.locator('[data-action="lab-line"]').count());await p.locator('[data-action="lab-line"]').first().click();assert.ok((await p.locator('#lab-editor').evaluate(el=>el.value.slice(el.selectionStart,el.selectionEnd))).includes('return'));console.log('Live API check completed.');results.push('LIVE syntax error: actual compiler diagnostics, plain-language help, and jump to source line.');
 await p.screenshot({path:path.join(root,'docs/preview-coding-compiler-error.png'),fullPage:true});
 const liveRequests=requests.length;const count=requests.length;await p.fill('#lab-editor',catalog.find(q=>q.id==='b1-add').solution);await p.reload();assert.equal(await currentBook(p),'cpp-book-01');assert.equal(await p.locator('#lab-editor').inputValue(),catalog.find(q=>q.id==='b1-add').solution);assert.equal(requests.length,count);results.push('Editing and reload do not send compiler requests; drafts and coding view persist.');
 await p.locator('[data-action="lab-reset"]').click();assert.equal(await p.locator('#lab-editor').inputValue(),catalog.find(q=>q.id==='b1-add').starter);await p.locator('[data-action="lab-undo"]').click();assert.equal(await p.locator('#lab-editor').inputValue(),catalog.find(q=>q.id==='b1-add').solution);
 const downloadPromise=p.waitForEvent('download');await p.locator('[data-action="lab-download"]').click();const download=await downloadPromise;const dl=path.join(root,'tests/coding-downloaded.cpp');await download.saveAs(dl);assert.ok((await fs.readFile(dl,'utf8')).includes('int main()'));results.push('Reset can be undone; downloaded question source includes a complete main driver.');
 await p.selectOption('#lab-question','playground');assert.ok((await p.locator('#lab-editor').inputValue()).includes('int main()'));assert.ok(await p.locator('[data-action="lab-test"]').isDisabled());
 await p.route('https://godbolt.org/api/**',r=>r.abort('internetdisconnected'));await p.locator('[data-action="lab-run"]').click();await p.waitForFunction(()=>!document.querySelector('[data-action="lab-run"]').disabled);assert.ok((await p.locator('#lab-results').textContent()).includes('draft is still here'));await p.unroute('https://godbolt.org/api/**');results.push('Simulated offline transport: failure keeps editor contents and explains connection problem.');
 // Imported source stays separate from the playground and the original course data.
 await chooseBook(p,'design-patterns-cpp');await p.locator('.book-chapter-dropdown[data-course="design-patterns-cpp"]').selectOption('1');await p.locator('[data-mode="code"]').click();await p.locator('[data-action="edit-in-lab"]').click();assert.ok((await p.locator('#lab-question').inputValue()).startsWith('source-'));assert.ok((await p.locator('#lab-editor').inputValue()).includes('main('));results.push('Existing worked C++ opens as a separate editable lab draft.');
 await chooseBook(p,'cpp-book-01');await p.locator('.book-chapter-dropdown[data-course="cpp-book-01"]').selectOption('1');await p.locator('[data-mode="code"]').click();await p.locator('[data-action="series-edit-in-lab"]').click();assert.ok((await p.locator('#lab-question').inputValue()).startsWith('worked-'));results.push('Book-series C++ listing opens in the same editor.');
 await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:path.join(root,'docs/preview-coding-mobile.png'),fullPage:true});results.push('390px mobile layout: no horizontal page overflow.');
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/coding-browser-results.json'),JSON.stringify({date:new Date().toISOString(),liveRequests,simulatedAbortRequests:1,compilerRequestsObserved:requests.length,results,errors},null,2));console.log(results.join('\n'));
}finally{await browser.close();}
