import {sourceData,sourceCoding} from './read-source.mjs';
// Deterministic UI edge cases. All compiler responses in this file are simulated.
import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import {chooseBook} from './book_test_helpers.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),q=sourceCoding().questions.find(q=>q.id==='b1-add');
let options={headless:true};if(process.env.CHROMIUM_MODULE){const{default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));options={...options,args:ch.args,executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
const browser=await chromium.launch(options),p=await browser.newPage({viewport:{width:1512,height:1100},reducedMotion:'reduce'}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
const endpoint='https://godbolt.org/api/**';let handler;
const setHandler=async fn=>{await p.unroute(endpoint);handler=fn;await p.route(endpoint,handler);};
const waitDone=()=>p.waitForFunction(()=>!document.querySelector('[data-action="lab-run"]').disabled);
try{
 await p.goto(process.env.STUDIO_URL||pathToFileURL(path.join(root,'dist-offline/index.html')).href);await chooseBook(p,'cpp-book-01');await p.locator('[data-mode="coding"]').click();await p.fill('#lab-editor',q.solution);
 await setHandler(async route=>{const source=route.request().postDataJSON().source,nonce=source.match(/@STUDY:([\w-]+)\|/)[1];const stdout=q.tests.map(t=>({text:`@STUDY:${nonce}|${t.id}|PASS|${Buffer.from(t.expected).toString('hex')}|${Buffer.from(t.expected).toString('hex')}`}));await route.fulfill({json:{code:0,didExecute:true,stdout,stderr:[],buildResult:{code:0,stderr:[]}}});});
 await p.locator('[data-action="lab-test"]').click();await waitDone();assert.equal(await p.locator('.lab-case.passed').count(),4);assert.ok((await p.locator('.lab-progress strong').first().textContent()).startsWith('1'));await p.reload();assert.ok((await p.locator('.lab-run-status').textContent()).includes('All checks passed'));assert.ok((await p.locator('.lab-progress strong').first().textContent()).startsWith('1'));results.push('A checked solution and the solved count persist through reload.');
 await p.locator('[data-action="settings"]').click();const dp=p.waitForEvent('download');await p.locator('[data-action="export-backup"]').click();const download=await dp;const backupPath=path.join(root,'tests/temporary-backup.json');await download.saveAs(backupPath);await p.locator('[data-action="close-dialog"]').click();const backup=JSON.parse(await fs.readFile(backupPath,'utf8'));assert.equal(backup.data.progress['cpp-book-01'].coding['b1-add'].code,q.solution);
 await p.fill('#lab-editor','// changed draft');await p.locator('#import-file').setInputFiles(backupPath);await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('restored'));assert.equal(await p.locator('#lab-editor').inputValue(),q.solution);assert.ok((await p.locator('.lab-progress strong').first().textContent()).startsWith('1'));await fs.unlink(backupPath);results.push('Export and restore preserve code, input, selected question, and passing state.');
 await p.locator('[data-action="settings"]').click();await p.locator('[data-action="reset-progress"]').click();await p.locator('[data-action="close-dialog"]').click();assert.equal(await p.locator('#lab-editor').inputValue(),q.solution);assert.ok((await p.locator('.lab-progress strong').first().textContent()).startsWith('0'));results.push('Reset learning progress clears passing records while retaining coding drafts.');
 await setHandler(route=>route.fulfill({json:{code:0,didExecute:true,stdout:[{text:'<img src=x onerror="window.labUnsafe=true">'}],stderr:[{text:'<script>window.labUnsafe=true</script>'}],buildResult:{code:0,stderr:[]}}}));await p.locator('[data-action="lab-run"]').click();await waitDone();assert.equal(await p.evaluate(()=>window.labUnsafe),undefined);assert.equal(await p.locator('#lab-results img,#lab-results script').count(),0);assert.ok((await p.locator('#lab-results').textContent()).includes('<img src=x'));await p.fill('#lab-stdin','8 9\n');assert.ok((await p.locator('.lab-run-status').textContent()).includes('Edited since'));results.push('Program output is escaped as text; changing stdin marks a run result as stale.');
 await setHandler(route=>route.fulfill({status:429,json:{message:'slow down'}}));await p.locator('[data-action="lab-run"]').click();await waitDone();assert.ok((await p.locator('#lab-results').textContent()).includes('rate-limited'));assert.equal(await p.locator('#lab-editor').inputValue(),q.solution);results.push('Rate-limit feedback preserves code and offers a retry.');
 await setHandler(route=>route.fulfill({json:{unexpected:'response'}}));await p.locator('[data-action="lab-run"]').click();await waitDone();assert.ok((await p.locator('#lab-results').textContent()).includes('unexpected response'));results.push('Malformed service responses never count as a successful run.');
 let pending;await setHandler(route=>{pending=route;});await p.locator('[data-action="lab-run"]').click();await p.waitForFunction(()=>document.querySelector('[data-action="lab-run"]').disabled);await p.locator('[data-action="lab-stop"]').click();assert.ok((await p.locator('#lab-results').textContent()).includes('remote service may finish'));if(pending)await pending.abort().catch(()=>{});results.push('Stop waiting cancels the client request and explains its remote limitation.');
 await p.locator('[data-action="lab-run"]').click();await p.selectOption('#lab-question','b1-positive');if(pending)await pending.abort().catch(()=>{});assert.equal(await p.locator('#lab-question').inputValue(),'b1-positive');assert.ok(!(await p.locator('#lab-results').textContent()).includes('All checks passed'));results.push('Switching questions cancels waiting and prevents another question from receiving a stale response.');
 await p.selectOption('#lab-question','b1-add');await p.locator('#lab-solution').evaluate(el=>el.open=true);await p.locator('[data-action="lab-use-solution"]').click();assert.equal(await p.locator('#lab-editor').inputValue(),q.solution);await p.locator('#lab-editor').focus();await p.locator('#lab-editor').evaluate(el=>el.setSelectionRange(0,0));await p.keyboard.press('Tab');assert.ok((await p.locator('#lab-editor').inputValue()).startsWith('    #include'));await p.keyboard.press('Shift+Tab');assert.equal(await p.locator('#lab-editor').evaluate(el=>document.activeElement===el),false);results.push('Reference solution loads explicitly; Tab indents and Shift+Tab leaves the editor.');
 // Clean viewport captures at useful reading positions, without transient toast or focused skip link.
 await p.selectOption('#lab-question','b1-maximum');await p.locator('#lab-question').focus();await p.locator('.coding-lab').scrollIntoViewIfNeeded();await p.evaluate(()=>document.querySelector('#toast').hidden=true);await p.screenshot({path:path.join(root,'docs/preview-coding-workspace-desktop.png')});
 await p.setViewportSize({width:390,height:844});assert.equal(await p.locator('[data-mode="book"]').isVisible(),true);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.lab-header').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(root,'docs/preview-coding-challenge-mobile.png')});await p.locator('#lab-editor').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(root,'docs/preview-coding-editor-mobile.png')});
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/coding-state-browser-results.json'),JSON.stringify({date:new Date().toISOString(),transport:'All compiler responses simulated in this edge-case suite; live checks are in coding-browser-results.json.',results,errors},null,2));console.log(results.join('\n'));
}finally{await browser.close();}
