import {sourceData,sourceCoding} from './read-source.mjs';
import {chooseBook,currentBook} from './book_test_helpers.mjs';
import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),data=sourceData(),books=data.courses.filter(c=>c.series);
let options={headless:true};if(process.env.CHROMIUM_MODULE){const{default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));options={...options,args:ch.args,executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
const browser=await chromium.launch(options),p=await browser.newPage({viewport:{width:1512,height:1100},reducedMotion:'reduce',acceptDownloads:true}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
await p.goto(process.env.STUDIO_URL||pathToFileURL(path.join(root,'dist-offline/index.html')).href);
for(const c of books){
 await chooseBook(p,c.id);await p.selectOption('#chapter-select','1');await p.locator('#mode-tabs [data-mode="uml"]').click();assert.equal(await p.locator('.focus-grid').count(),2);assert.ok(await p.locator('.uml-image').evaluateAll(a=>a.every(i=>i.complete&&i.naturalWidth>0)));
 await p.locator('.diagram-section').screenshot({path:path.join(root,`docs/preview-cpp-book-${c.series.number}-uml.png`)});await p.locator('.focus-grid .answer-reveal summary').first().click();await p.locator('.focus-grid').first().screenshot({path:path.join(root,`docs/preview-cpp-book-${c.series.number}-focus.png`)});
 await p.locator('[data-action="expand-diagram"]').first().click();assert.ok(await p.locator('dialog img').evaluate(i=>i.complete&&i.naturalWidth>0));await p.locator('[data-action="close-dialog"]').click();
 await p.selectOption('#chapter-select','2');assert.ok(await p.locator('[data-action="series-uml-start"]').count());await p.locator('[data-action="series-uml-start"]').click();assert.equal(await p.locator('#chapter-select').inputValue(),'1');
 await p.locator('#mode-tabs [data-mode="book"]').click();const pending=p.waitForEvent('download');await p.locator('[data-action="series-download-book"][data-kind="pdf"]').click();const dl=await pending;assert.equal(crypto.createHash('sha256').update(await fs.readFile(await dl.path())).digest('hex'),c.series.assets.pdf.sha256);
 const e=c.series.listings.find(x=>x.chapter===1&&x.completeCandidate);await p.locator('#mode-tabs [data-mode="code"]').click();await p.selectOption('#series-code-select',e.id);const codePending=p.waitForEvent('download');await p.locator('[data-action="series-download-code"]').click();const codeDL=await codePending;assert.equal(await fs.readFile(await codeDL.path(),'utf8'),await fs.readFile(path.join(root,e.filename),'utf8'));
}
results.push('All eight diagram studies, focused panels, full-size views, fallback navigation, PDF downloads, and source-code downloads');console.log('PASS',results.at(-1));
await chooseBook(p,'cpp-book-08');await p.selectOption('#chapter-select','1');await p.locator('#mode-tabs [data-mode="outline"]').click();await p.screenshot({path:path.join(root,'docs/preview-cpp-series-final-map.png')});
await p.locator('#mode-tabs [data-mode="scenarios"]').click();await p.fill('#series-response','Verify the count stays within 0–2.');await p.locator('[data-action="series-rate"][data-rating="again"]').click();await p.locator('[data-action="settings"]').first().click();let pending=p.waitForEvent('download');await p.locator('[data-action="export-backup"]').click();let dl=await pending;const backup=await dl.path();await p.locator('[data-action="close-dialog"]').click();await p.fill('#series-response','temporary change');await p.locator('#import-file').setInputFiles(backup);await p.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('restored'));assert.equal(await p.locator('#series-response').inputValue(),'Verify the count stays within 0–2.');await p.selectOption('#scope-select','review');assert.ok((await p.locator('.series-self-check').textContent()).includes('practice again'));results.push('New practice answers and review queue survive backup/restore');
// Source internal reference must navigate to the target reading block.
const c=books.find(c=>c.id==='cpp-book-06');const walk=nodes=>(nodes||[]).flatMap(n=>typeof n==='string'?[]:[n,...walk(n.children)]);let linked;
for(const t of c.topics)for(const b of t.blocks){const a=walk(b.rich).find(n=>n.tag==='a'&&n.href?.includes('#')&&!/^[a-z][a-z0-9+.-]*:/i.test(n.href));if(a){linked={t,b,a};break;}if(linked)break;}
assert.ok(linked,'An EPUB reference fixture is required');
if(linked){await chooseBook(p,c.id);await p.selectOption('#chapter-select',String(linked.t.chapter));await p.locator('#mode-tabs [data-mode="outline"]').click();await p.locator(`.chapter-map-list [data-id="${linked.t.id}"]`).click();const button=p.locator('.source-reader [data-action="series-reference"]').first();assert.ok(await button.count());const target=await button.getAttribute('data-block');await button.click();assert.ok(await p.locator('#series-'+target).count());results.push('EPUB internal reference opens its exact target block');}
// Export and re-import a full book; safe rich content and source exercises must survive.
await chooseBook(p,'cpp-book-05');await p.locator('[data-action="settings"]').first().click();pending=p.waitForEvent('download');await p.locator('[data-action="export-pack"]').click();dl=await pending;const pack=await dl.path();await p.locator('[data-action="close-dialog"]').click();await p.locator('#import-file').setInputFiles(pack);await p.waitForFunction(()=>document.querySelector('#book-dropdowns').dataset.currentCourse.startsWith('cpp-book-05-import-'));await p.selectOption('#chapter-select','1');await p.locator('#mode-tabs [data-mode="outline"]').click();assert.ok(await p.locator('.map-section').count());await p.locator('#mode-tabs [data-mode="code"]').click();assert.ok((await p.locator('.full-code').textContent()).includes('int add'));await p.locator('#mode-tabs [data-mode="scenarios"]').click();assert.ok(await p.locator('#series-response').count());await p.locator('.series-answer summary').click();results.push('Book export/import preserves rich reading, code, diagrams, and practice');
await p.setViewportSize({width:390,height:844});await p.locator('#mode-tabs [data-mode="uml"]').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:path.join(root,'docs/preview-cpp-series-mobile-uml.png')});
assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/series-advanced-browser-results.json'),JSON.stringify({results,errors},null,2));await browser.close();
