"""Original chapter-specific application questions; grounded in the supplied lectures."""
DATA = r'''1|A program prints the expected answer once. What does that observation establish?|That one observed run produced that output.|The program is correct for every input.|The program has no undefined behavior.|The compiler proved the program correct.|One successful run is evidence about that run. Broader claims require explicit contracts, assumptions, and additional evidence.
2|A POSIX read returns -1. The caller immediately stores it in size_t. What should change?|Check the signed result before converting a successful count.|Use unsigned everywhere to prevent errors.|Treat the converted value as a large successful read.|Assume a pointer parameter carries the buffer length.|The signed result represents both counts and errors. Conversion to an unsigned type loses the negative error indication.
3|A packed byte has unrelated flags. How should you replace just one field?|Clear the field’s mask, then OR in the masked new bits.|OR the new value into the byte without clearing old field bits.|Assign the new field value to the whole byte.|Clear every bit before writing the field.|Clearing only the target mask removes its old bits while preserving other fields. Mask the incoming value so it cannot change neighbors.
4|Before allocating count * element_size bytes, which guard prevents unsigned multiplication overflow?|For nonzero element_size, require count <= SIZE_MAX / element_size.|Multiply first and check whether the unsigned answer is negative.|Assume unsigned arithmetic cannot wrap.|Only check that count is positive.|Unsigned arithmetic wraps modulo its range. A division-based bound checks representability before multiplication loses information.
5|A decimal 0.1 stored in binary floating point prints a nearby value. Why?|Its exact value generally has no finite binary expansion.|Every floating-point value is a random approximation.|The decimal input necessarily overflowed.|IEEE 754 requires all decimal fractions to be exact.|Finite binary floating-point formats cannot represent every decimal fraction. Rounding selects a nearby representable value.
6|A structure’s sizeof exceeds the sum of its member sizes. What is a plausible reason?|Alignment padding between members or at the end.|sizeof always counts heap allocations too.|The compiler must be duplicating each field.|All structures have a universal fixed size.|Alignment can require unused bytes so members and successive array elements meet placement requirements. Layout is not a universal wire format.
7|A pointer has advanced exactly one past its array. Which operation is permitted?|Use it as an end position without dereferencing it.|Read the element at that pointer.|Advance it arbitrarily farther and dereference it.|Assume adjacent storage belongs to the array.|C and C++ allow a one-past pointer for range calculations and comparisons within the relevant array rules, but not for dereferencing.
8|A program prints different stack addresses on two launches. What follows?|Address variation alone does not disprove the object’s lifetime or placement model.|The object necessarily moved during the same call.|The stack cannot contain local objects.|Every printed virtual address is a physical RAM location.|A conceptual process layout does not promise fixed numeric addresses across runs. Virtual addresses and physical residency are different claims.
9|realloc fails while growing a nonzero C buffer. How should the caller preserve its allocation?|Store the result in a temporary and keep the original pointer on failure.|Overwrite the only original pointer before checking.|Free the original pointer and continue using it.|Assume failure transfers ownership to the caller’s temporary.|For the stated nonzero request, failure leaves the original allocation valid. Overwriting its only owning pointer can leak it.
10|An allocator has ample total free bytes but no large contiguous block. What problem is this?|External fragmentation.|A guarantee that every allocation must succeed.|Proof that all free space is one contiguous region.|A floating-point rounding error.|External fragmentation separates free regions. Total free bytes alone do not establish that a particular contiguous request can be served.
11|A pointer is read after its allocation was freed, but the old value still appears. Is that valid?|No; retained bytes do not extend the object’s lifetime.|Yes, until the bytes visibly change.|Yes, if the pointer is const.|Yes, if the read does not crash.|A use-after-free violates the lifetime contract. A plausible value or absence of a crash does not make the access valid.
12|Two processors implement the same ISA. Must an instruction take the same time?|No; the ISA contract does not fix every microarchitectural timing choice.|Yes; ISA compatibility requires identical latency.|Yes; all instructions take one cycle.|No; they must therefore run different binaries.|An ISA describes the programmer-visible machine contract. Implementations may use different pipelines, caches, and execution resources.
13|On x86-64, what happens to the high half of RAX when EAX is written?|It is zeroed.|It is always preserved.|It becomes the sign extension of bit 31 in every case.|The write affects an unrelated register.|An EAX write produces a 32-bit result and clears the upper 32 bits of RAX. Narrower partial-register writes have different rules.
14|An x86-64 LEA instruction computes an address expression. Does it read memory at that address?|No; it computes the effective-address value.|Yes; it always loads the pointed-to byte.|Yes; it always loads a whole cache line as its architectural result.|Only if the result is stored in a register.|LEA performs address arithmetic. A memory-load instruction is needed to fetch the value stored at that computed address.
15|Integer division is used to estimate an average. What information may be lost?|The fractional part of the result.|Every input’s sign before evaluation.|The number of operands in the expression.|All high bits of both operands unconditionally.|Integer division produces an integer quotient. Its rounding rule and overflow or division-by-zero preconditions must be understood before using it as a numeric model.
16|The same bit patterns are compared with signed and unsigned conditional branches. Can the decisions differ?|Yes; signedness changes the comparison interpretation.|No; branch conditions ignore signedness.|No; only variable names affect the decision.|Yes, but only if the source fails to compile.|Signed and unsigned comparisons interpret high-bit-set values differently and use different condition-code tests. Match the branch to the intended value domain.
17|A function overwrites a callee-saved register and returns without restoring it. What fails?|The calling convention’s preservation contract.|Only the source-code indentation.|The guarantee that every register is caller-saved.|The requirement that all functions must inline.|The caller may rely on a callee-saved register retaining its value across the call. Save and restore it when the callee needs to modify it.
18|A local computation vanishes from optimized assembly because its result is unused. Why can that be allowed?|It has no required observable effect under the language rules.|The optimizer may delete any output it dislikes.|Optimization disables all language guarantees.|A debugger display is always the program’s semantic contract.|Optimization may change implementation while preserving required observable behavior. Dead computations need not remain as instructions.
19|An ordinary user program needs a privileged OS service. What is the normal boundary?|A controlled kernel entry through the supported system-call interface.|Direct unrestricted modification of kernel memory.|Changing a C++ variable named privilege to true.|Calling any arbitrary kernel address as a normal function.|User mode cannot freely perform privileged work. The OS exposes checked entry paths with defined arguments, results, and failure behavior.
20|A system call enters privileged code. What must the kernel still do?|Validate user-controlled arguments and access conditions.|Trust every address because the caller compiled successfully.|Treat a user pointer as proof of ownership.|Skip error handling because the entry mechanism is protected.|Controlled entry changes execution privilege; it does not make user inputs trustworthy or guarantee the requested operation can succeed.
21|Two independent processes both use virtual address 0x1000. Must they access the same byte?|No; address-space context affects the mapping.|Yes; the numeric virtual address uniquely identifies physical storage.|Yes; process IDs have no role in isolation.|No; virtual addresses cannot repeat across processes.|Each process can have its own virtual-to-physical mappings. Equal virtual numbers do not by themselves imply shared storage.
22|A virtual range is mapped in a process. Does that alone prove every page is resident in RAM?|No; mapping and present physical backing are different states.|Yes; mapping always eagerly loads all bytes.|Yes; mapped memory cannot fault.|No; mapped ranges can never contain RAM-backed pages.|A valid virtual mapping can use demand paging. Translation, permissions, and residency must be distinguished.
23|A page size is 4096 bytes. How is address 0x1234 split?|Virtual page 1 and offset 0x234.|Virtual page 0x1234 and offset 0.|Virtual page 0x234 and offset 1.|Virtual page 4096 and offset 0x1234.|Divide by the page size to find the page number; the remainder is the within-page offset. Here 0x1000 + 0x234 = 0x1234.
24|A page-table entry grants read access but denies writes. What should a store require?|A permission check that can reject the write.|Ignoring permissions after the address is translated.|Changing the source pointer to const.|Assuming a present page permits every access.|Page-table state includes access permissions as well as translation information. A present mapping is not a promise of write permission.
25|The TLB misses for a valid resident page. Must disk I/O occur?|No; the translation may be recovered by a page-table walk.|Yes; every TLB miss is a disk page fault.|Yes; cached data must be discarded first.|No; the instruction must instead always fail.|A TLB caches translations. Its miss can be resolved from valid page-table state without fetching the page’s contents from storage.
26|A first write to a copy-on-write mapping faults. What can the OS do?|Create private writable backing and retry the access when policy permits.|Treat every page fault as a fatal hardware defect.|Allow a write to another process’s private bytes without isolation.|Declare that a fault proves the virtual address is unmapped.|Some faults are expected mechanisms for demand paging or copy-on-write. The cause and mapping policy determine whether recovery is valid.
27|Why does a hierarchy combine small fast storage with larger slower storage?|It trades capacity, cost, and access time while exploiting reuse.|Every level has identical latency and cost.|Larger capacity always implies lower latency.|The hierarchy removes the need to move data.|Different levels have different costs and capacities. Reused data near the processor can reduce average access time.
28|A loop accesses adjacent elements of a contiguous array. Which property may it exploit?|Spatial locality.|A guarantee of zero cache misses.|The absence of all dependencies.|A universal promise that every loop is fast.|Nearby addresses can share a fetched cache line. Benefits still depend on access size, layout, working set, and the machine.
29|In a direct-mapped cache, two frequently used blocks map to the same set. What can happen?|They repeatedly evict one another.|They can occupy arbitrary alternative ways in that set.|The tag comparison becomes unnecessary.|Direct mapping guarantees both remain resident.|A direct-mapped set has one placement slot. Alternating colliding blocks can cause repeated conflict misses.
30|A cold cache reads the same block twice with no intervening eviction. What is the simple read-model trace?|Miss, then hit.|Hit, then miss.|Hit, then hit.|Miss, then compulsory miss again.|The first demand brings in the block. The second read hits while the valid block remains resident in the modeled cache.
31|A full set uses true LRU replacement. Which block does it choose as the victim?|The least recently used resident block.|The block with the smallest numeric address in every case.|The most recently used block by definition.|A randomly selected block regardless of policy.|LRU tracks recency within the replacement domain. The least recently used resident entry is selected when a replacement is needed.
32|Hit time is 2 ns, miss rate 5%, and additional miss penalty 40 ns. What is simple AMAT?|4 ns.|42 ns.|2 ns.|200 ns.|AMAT = hit time + miss rate × additional penalty = 2 + 0.05 × 40 = 4 ns. This is a stated simplified model, not a complete machine timing prediction.
33|write returns a positive count smaller than requested. What should a robust caller consider?|Advance by that count and handle the remaining bytes according to the interface.|Assume all requested bytes were written.|Retry the whole buffer from byte zero unconditionally.|Interpret every short positive result as -1.|A successful short write reports progress, not necessarily completion. Track the remaining range and handle errors or retry conditions explicitly.
34|dup creates another descriptor for an open file. What is commonly shared on POSIX?|The underlying open file description, including its file offset.|A guarantee of two independent file offsets.|The numeric descriptor value itself.|Every process’s entire descriptor table.|Duplicated descriptors refer to the same open file description. Distinguish descriptor numbers from the object they reference.
35|printf output is buffered in user space. Does returning from printf prove durable storage?|No; buffering, kernel acceptance, and durability are separate claims.|Yes; formatted output always forces stable storage.|Yes; stdout cannot be buffered.|No; successful printf never copies any data.|Library buffering can delay system calls, and a successful write does not itself establish durability. Use the guarantees appropriate to the destination.
36|A file-backed mapping is accessed beyond the file’s valid backing after truncation. What must the design consider?|A fault such as SIGBUS on the stated POSIX/Linux setting.|A guarantee that all mapped bytes remain valid forever.|Automatic growth of the file for every read.|That mmap eliminates bounds and lifetime requirements.|Mapping length and file backing can diverge. File truncation can invalidate accessible backing even while a virtual mapping remains.
37|After fork, the child modifies an ordinary private variable. Must the parent observe that new value?|No; ordinary private process memory is logically separate.|Yes; all inherited memory is shared for writes.|Yes; fork creates only another thread.|No; the child cannot modify any variable.|Parent and child have separate address spaces for ordinary private mappings. Copy-on-write is an implementation technique that preserves that isolation.
38|exec succeeds in a process. What happens to the calling program image?|It is replaced; success does not return to the old call site.|A new child must always be created.|Both old and new main functions continue together.|The old program resumes immediately after exec.|exec replaces the current process image. fork and exec serve different roles; failure returns through the old program’s error path.
39|A child terminates but its parent has not collected its status. What may remain?|A zombie status record awaiting collection.|A fully running child doing normal computation.|All of the child’s heap allocations as live parent objects.|A new executable image automatically started by wait.|Termination releases most execution resources, but exit status can remain until the parent or another responsible process reaps it.
40|A pipe reader never receives EOF after the intended writer exits. What should you check?|Whether some process still holds an open write end.|Whether the reader’s buffer is too large to permit EOF.|Whether EOF requires a newline character.|Whether every read must return a full buffer.|EOF depends on all relevant write-end references being closed and buffered bytes being consumed. Inherited or duplicated descriptors can keep a writer reference alive.
41|A signal handler calls an arbitrary library routine using locks. What is the concern?|The routine may not be async-signal-safe and can deadlock or corrupt state.|Signal handlers automatically make all routines reentrant.|The handler runs only between complete library calls.|A signal guarantees mutual exclusion with the interrupted code.|A handler can interrupt code holding internal state or locks. Use the documented signal-safe operations and an appropriate handoff design.
42|A shell implements cd by changing directory only inside a short-lived child. What is wrong?|The shell parent’s working directory does not change.|Every child directory change automatically propagates to its parent.|cd requires replacing the operating system.|The child cannot ever call chdir.|State-changing built-ins such as cd must affect the persistent shell process when that is the intended behavior.
43|Two operations overlap in time. Does concurrency require simultaneous execution on two cores?|No; interleaving on one core is also concurrency.|Yes; concurrency and parallel execution are identical.|Yes; every concurrent operation needs a dedicated CPU.|No; concurrent operations cannot share resources.|Concurrency concerns overlapping progress and interactions. Parallelism concerns execution at the same instant; one core can interleave concurrent tasks.
44|Two threads in one process use a global object. What should the design assume?|They can share that object and require synchronization for conflicting accesses.|Every thread has a private copy of all globals.|Thread creation makes all accesses atomic.|A thread has a wholly separate process address space.|Threads commonly share process memory while having their own execution state and stacks. Shared mutable objects need an explicit access protocol.
45|Two threads increment the same non-atomic C++ int without synchronization. What is the issue?|A data race with undefined behavior.|A guaranteed final value equal to one of the increments.|A safe operation because int fits in a register.|A guaranteed compiler error.|Conflicting unsynchronized accesses, with at least one write, create a C++ data race. A hardware-sized operation does not establish a language-level synchronization contract.
46|An atomic ready flag publishes ordinary data. What may be needed beyond atomicity of the flag itself?|An appropriate release/acquire ordering protocol.|Relaxed atomics always publish all preceding ordinary writes.|volatile alone guarantees cross-thread publication.|Atomicity makes the entire program sequential automatically.|Atomicity prevents tearing for that object; ordering controls visibility relationships. A correctly paired release/acquire protocol can establish the required happens-before relation.
47|A mutex protects one write path but readers bypass it. Is the shared-state protocol complete?|No; all conflicting access paths must follow the synchronization contract.|Yes; locking a single writer automatically protects every reader.|Yes; const reads never participate in data races.|No; mutexes can only protect stack variables.|Mutual exclusion works only when relevant participants use the protocol. Unsynchronized reads can still conflict with protected writes.
48|A condition-variable wait wakes up. What should the consumer do before consuming?|Recheck the shared predicate while holding the lock.|Assume a notification guarantees an item is still available.|Use if once and never check again.|Unlock first, then inspect an unprotected queue.|Wakeups may be spurious, and another consumer may change the predicate first. Wait in a predicate loop with the required lock discipline.
49|A bounded queue is full when a producer arrives. What must the protocol define?|Waiting or rejection, wakeups, and shutdown behavior.|Permission to overwrite unread items silently in every design.|That consumers can never fall behind.|That a mutex alone specifies all queue semantics.|A capacity bound requires explicit behavior for full and empty states. Synchronization must preserve queue invariants and let shutdown wake blocked participants.
50|Two threads acquire locks A and B in opposite orders. What risk appears?|Circular waiting and deadlock.|A guarantee that the scheduler will always fix the order.|A compile-time type error in all C++ implementations.|Automatic lock release as soon as another thread waits.|Opposite acquisition orders can create a cycle. A consistent global order or another proven acquisition protocol removes that particular cycle.
51|TCP receive returns half an application message. What should the application remember?|TCP is a byte stream; the application needs framing and accumulation.|Every send must match exactly one receive.|A short receive proves the connection is corrupt.|TCP inserts the application’s message lengths automatically.|TCP preserves an ordered byte stream, not application message boundaries. Define framing and collect enough bytes before interpreting a complete message.
52|A server handles each client synchronously before accepting more work. What can a slow client cause?|Head-of-line blocking for unrelated clients in that design.|Guaranteed fairness without scheduling.|Automatic unlimited parallelism.|A proof that the network protocol is invalid.|A serial service path lets one slow operation delay others. Concurrency can improve responsiveness but requires resource and synchronization limits.
53|A nonblocking socket was reported ready, but a read now returns EAGAIN. What is appropriate?|Handle the would-block result and return to the event protocol.|Treat readiness as a permanent guarantee of data.|Busy-spin forever without checking state.|Assume the kernel violated the API.|Readiness is time-sensitive and can change before an operation. Nonblocking code must handle would-block, partial progress, closure, and errors.
54|An optimization benchmark reports one unusually fast run. What is a stronger method?|Repeat under controlled conditions and report variability with the workload.|Select only the fastest result and call it universal.|Change input size on every comparison without recording it.|Treat wall-clock time as proof of semantic correctness.|Performance evidence depends on workload, build, warmup, environment, and variability. Repeated comparable trials support a narrower and more defensible conclusion.
55|Amdahl’s model says 20% of runtime is unaffected by an optimization. What is the maximum overall speedup?|5×, even if the other 80% becomes infinitely fast.|Unlimited overall speedup.|Exactly 1.2× in every case.|80× by definition.|The unchanged fraction sets a lower bound on total time. Maximum speedup is 1 / 0.20 = 5 under this model.
56|A profile shows most samples in one function. What should you do before rewriting it?|Understand the workload and verify that the proposed change targets the measured cost.|Assume every line in that function is equally expensive.|Conclude the function is semantically incorrect.|Ignore all caller behavior and measurement overhead.|A profile is evidence about a particular execution and measurement method. Attribute cost carefully, form a hypothesis, then measure a controlled change.
57|Untrusted input supplies a length used to copy into a fixed buffer. What boundary must be checked?|The valid input range, destination capacity, and any size arithmetic before copying.|Only whether the pointer value is nonzero.|Only whether the input is printable text.|Only whether a previous run succeeded.|Memory-safe copying requires valid bounds and lifetimes, with representable length calculations. A non-null pointer alone does not establish a safe range.
58|ASLR is enabled. Does that remove the need to repair a buffer overflow?|No; mitigation changes exploit conditions but does not repair the invalid access.|Yes; randomized addresses make every memory access valid.|Yes; ASLR proves the program has no vulnerabilities.|No; ASLR requires all bounds checks to be removed.|Exploit mitigations can reduce attack reliability or available techniques. They do not restore the violated bounds or lifetime contract.
59|A function acquires a resource, then a later operation fails. What must its error path preserve?|Ownership and cleanup rules, plus the documented state guarantee.|Only the success-path return value.|Every partially acquired resource indefinitely.|A promise to ignore the failure and continue.|Robustness includes exceptional and partial-progress paths. Release what the function owns and leave state consistent with its stated failure guarantee.
60|Compilation succeeds, but the linker reports an unresolved function. Which stage should you inspect?|Object definitions, symbol names, and the link inputs or order.|Only the program’s eventual cache hit rate.|Only the input data supplied after launch.|Assume successful compilation already proved symbol resolution.|Separate compilation can leave external references unresolved. Linking must find compatible definitions and resolve the relevant symbols.
61|A systems program produces correct output but leaks descriptors after failures. Has the whole-system contract been met?|No; resource ownership and error paths are part of correctness.|Yes; visible output is the only possible contract.|Yes; the OS must instantly close every leaked descriptor during execution.|No; correct output and resource cleanup are mutually exclusive.|A complete system must connect functional results with resource, lifetime, failure, and performance requirements. Passing one output test does not establish those other properties.'''
ROWS={int(p[0]):p[1:] for line in DATA.splitlines() if (p:=line.split('|'))}
assert len(ROWS)==61 and all(len(x)==6 for x in ROWS.values())
