import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),data=JSON.parse(await fs.readFile(path.join(root,'src/content.json'),'utf8')),c=data.courses.find(c=>c.id==='systems-programming');
let options={headless:true};if(process.env.CHROMIUM_MODULE){const{default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));options={...options,args:ch.args,executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
const b=await chromium.launch(options),p=await b.newPage({viewport:{width:1512,height:1100},reducedMotion:'reduce',acceptDownloads:true}),errors=[],results=[];
p.on('pageerror',e=>errors.push(e.message));const ok=s=>{results.push(s);console.log('PASS',s)};
await p.goto(pathToFileURL(path.join(root,'dist/index.html')).href);await p.selectOption('#course-select',c.id);assert.equal(await p.locator('#mode-tabs button').count(),6);
for(let n=1;n<=61;n++){
 await p.selectOption('#chapter-select',String(n));await p.locator('#mode-tabs [data-mode="outline"]').click();assert.equal(await p.locator('.map-section').count(),5);
 await p.locator(`.chapter-map-list [data-id="SYS${String(n).padStart(2,'0')}.09"]`).click();assert.equal(await p.locator('.lesson-explanation .answer-reveal').count(),2);await p.locator('.lesson-explanation .answer-reveal').last().locator('summary').click();assert.ok((await p.locator('.lesson-explanation').textContent()).includes(c.examples[n].lab.checks[0]));
 await p.locator('#mode-tabs [data-mode="uml"]').click();assert.equal(await p.locator('.uml-image').count(),1+c.diagrams[n].extra_overviews.length);assert.equal(await p.locator('.focus-grid').count(),c.diagrams[n].focus.length);assert.ok(await p.locator('.uml-image').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)));await p.locator('.focus-grid .answer-reveal summary').first().click();assert.ok((await p.locator('.focus-grid').first().textContent()).includes(c.diagrams[n].focus[0].explain[0]));
 await p.locator('#mode-tabs [data-mode="code"]').click();for(const k of ['examples','exercises','solutions']){await p.locator(`[data-action="code-kind"][data-kind="${k}"]`).click();assert.ok((await p.locator('.full-code').textContent()).includes('int main()'));assert.equal(await p.locator('.answer-reveal pre code').nth(1).textContent(),c.examples[n][k].output);if(k!=='examples')assert.equal(await p.locator('.lab-checks li').count(),c.examples[n].lab.checks.length);}
 assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
}
ok('All 61 chapter maps, bug exercises, UML views, theory panels, and 183 code variants render correctly');
for(const n of [2,30,49,61]){
 await p.selectOption('#chapter-select',String(n));await p.locator('#mode-tabs [data-mode="outline"]').click();await p.screenshot({path:path.join(root,`docs/preview-systems-depth-${n}-map.png`)});
 await p.locator('#mode-tabs [data-mode="uml"]').click();await p.locator('.diagram-section').first().screenshot({path:path.join(root,`docs/preview-systems-depth-${n}-uml.png`)});await p.locator('.focus-grid .answer-reveal summary').first().click();await p.locator('.focus-grid').first().screenshot({path:path.join(root,`docs/preview-systems-depth-${n}-focus.png`)});
 if(c.diagrams[n].extra_overviews.length)await p.locator('.diagram-section').last().screenshot({path:path.join(root,`docs/preview-systems-depth-${n}-relationships.png`)});
}
await p.locator('#mode-tabs [data-mode="code"]').click();await p.locator('[data-action="code-kind"][data-kind="solutions"]').click();const pending=p.waitForEvent('download');await p.locator('[data-action="download-code"]').click();const dl=await pending,tmp=path.join(root,'tests/systems-capstone-download.cpp');await dl.saveAs(tmp);assert.equal(await fs.readFile(tmp,'utf8'),c.examples[61].solutions.code);await fs.unlink(tmp);ok('Capstone solution download matches the packaged source exactly');
await p.selectOption('#chapter-select','30');await p.locator('#mode-tabs [data-mode="outline"]').click();await p.locator('.chapter-map-list [data-id="SYS30.09"]').click();await p.locator('.lesson-explanation .answer-reveal').last().locator('summary').click();await p.screenshot({path:path.join(root,'docs/preview-systems-depth-exercise.png')});
await p.setViewportSize({width:390,height:844});for(const mode of ['outline','uml','code']){await p.locator(`#mode-tabs [data-mode="${mode}"]`).click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>document.activeElement?.blur());await p.screenshot({path:path.join(root,`docs/preview-systems-depth-mobile-${mode}.png`)});}
ok('Mobile reading, diagrams, and code stay within the page width');
await p.setViewportSize({width:1512,height:1100});await p.locator('[data-action="book-glossary"]').first().click();await p.fill('#glossary-search','shutdown');assert.ok((await p.locator('#glossary-results').textContent()).includes('Shutdown protocol'));ok('Systems glossary is searchable with chapter links');
assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/systems-depth-browser-results.json'),JSON.stringify({results,errors},null,2));await b.close();
