import {sourceData,sourceCoding} from './read-source.mjs';
import {chooseBook,currentBook} from './book_test_helpers.mjs';
import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const content=sourceData();const c=content.courses.find(c=>c.id==='systems-programming');
let options={headless:true};if(process.env.CHROMIUM_MODULE){const{default:ch}=await import(pathToFileURL(process.env.CHROMIUM_MODULE));options={...options,args:ch.args,executablePath:process.env.CHROMIUM_PATH||await ch.executablePath()};}
const b=await chromium.launch(options),p=await b.newPage({viewport:{width:1512,height:1000},reducedMotion:'reduce',acceptDownloads:true});const errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));const ok=s=>{results.push(s);console.log('PASS',s)};
await p.goto(process.env.STUDIO_URL||pathToFileURL(path.join(root,'dist-offline/index.html')).href);assert.equal((await p.locator('.book-chapter-dropdown').count())+1,content.courses.length);await p.selectOption('#chapter-select','1');await p.locator('#personal-note').fill('Design patterns note');
await chooseBook(p,'systems-programming');assert.equal(await p.locator('#all-count').textContent(),String(c.topics.length));assert.equal(await p.locator('#mode-tabs button').count(),6);assert.equal(await p.locator('#chapter-select option').count(),c.chapters.length+2);assert.ok(!(await p.locator('#course-domain-count').textContent()).includes('22 patterns'));ok('Separate systems course and accurate navigation');
await p.locator('#personal-note').fill('Systems note');await p.locator('[data-action="reviewed"]').click();await p.reload();assert.equal(await p.locator('#personal-note').inputValue(),'Systems note');await chooseBook(p,'design-patterns-cpp');assert.equal(await p.locator('#personal-note').inputValue(),'Design patterns note');assert.equal(await p.locator('#mode-tabs button').count(),5);await p.locator('#mode-tabs [data-mode="uml"]').click();assert.ok(await p.locator('.uml-image').count());await chooseBook(p,'systems-programming');assert.equal(await p.locator('.lesson-heading').count(),1);ok('Independent notes survive reload; course changes reset incompatible modes');
for(let n=1;n<=61;n++){await p.selectOption('#chapter-select',String(n));for(const mode of ['outline','flashcards','scenarios','lectures']){await p.locator(`#mode-tabs [data-mode="${mode}"]`).click();if(mode==='outline')assert.equal(await p.locator('.lesson-heading').count(),1);if(mode==='flashcards')assert.equal(await p.locator('.deck-card').count(),1);if(mode==='scenarios')assert.equal(await p.locator('.choice').count(),4);if(mode==='lectures')assert.equal(await p.locator('#lecture-slide-select option').count(),c.lectures[n].slideCount+1);}}
ok('All 61 chapters render lessons, cards, cases, and original lecture materials');
await p.selectOption('#chapter-select','30');await p.locator('#mode-tabs [data-mode="lectures"]').click();for(const kind of ['presentation','transcript']){const pending=p.waitForEvent('download');await p.locator(`[data-action="download-lecture"][data-kind="${kind}"]`).click();const d=await pending;const l=c.lectures[30],name=kind==='presentation'?l.presentationName:l.transcriptName;assert.equal(d.suggestedFilename(),name);const file=path.join(root,'tests/download-check');await d.saveAs(file);assert.deepEqual(await fs.readFile(file),await fs.readFile(path.join(root,'systems_source/Chapter_30',name)));await fs.unlink(file);}ok('PowerPoint and transcript downloads byte-match the supplied files');
await p.selectOption('#lecture-slide-select','SP30.004');assert.ok((await p.locator('.lesson-heading').textContent()).includes('Cache hit'));await p.locator('.source-material > summary').click();await p.locator('.source-material .answer-reveal summary').first().click();assert.ok((await p.locator('.source-material').textContent()).includes('SIXTH-GRADE EXPLANATION'));await p.evaluate(()=>{document.activeElement?.blur();scrollTo(0,0)});await p.screenshot({path:path.join(root,'docs/preview-systems-outline.png')});
await p.locator('#mode-tabs [data-mode="scenarios"]').click();const sc=c.topics.find(t=>t.chapter===30&&t.scenario).scenario;await p.locator('.choice').nth(sc.correctIndex).click();await p.locator('[data-action="check-answer"]').click();assert.ok((await p.locator('.feedback').textContent()).includes('first demand'));await p.screenshot({path:path.join(root,'docs/preview-systems-scenarios.png')});ok('Slide jump, full transcript, and explained practice answer');
await p.locator('#mode-tabs [data-mode="lectures"]').click();await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(root,'docs/preview-systems-lectures.png')});await p.setViewportSize({width:390,height:844});await p.evaluate(()=>document.activeElement?.blur());assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:path.join(root,'docs/preview-systems-mobile.png')});ok('Mobile lecture layout stays within the page width');
await p.setViewportSize({width:1512,height:1000});await p.locator('[data-action="settings"]').first().click();const pending=p.waitForEvent('download');await p.locator('[data-action="export-backup"]').click();const dl=await pending;const file=path.join(root,'tests/systems-backup-check.json');await dl.saveAs(file);const backup=JSON.parse(await fs.readFile(file,'utf8'));backup.data.progress['systems-programming'].reviewed=c.topics.slice(0,1100).map(t=>t.id);await fs.writeFile(file,JSON.stringify(backup));await p.locator('[data-action="close-dialog"]').click();p.on('dialog',d=>d.accept());await p.locator('#import-file').setInputFiles(file);await p.waitForFunction(()=>document.querySelector('#sidebar-progress').textContent.includes('1100 of 2691'));await fs.unlink(file);ok('Backup restores more than 1000 reviewed lessons without truncation');
assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'tests/systems-browser-results.json'),JSON.stringify({results,errors},null,2));await b.close();
