// Linux course views share the existing navigation, notes and review progress.
function linuxCourse(){return course().id==='linux-system-administration';}
function linuxCleanDrafts(value){return Object.fromEntries(Object.entries(value&&typeof value==='object'?value:{}).filter(([key,code])=>/^\d{1,2}$/.test(key)&&typeof code==='string').map(([key,code])=>[key,code.slice(0,60000)]));}
function linuxImage(value){
  if(value?.$asset&&/^assets\/linux-admin\/ch\d+\.svg$/.test(value.$asset))return value.$asset;
  return typeof value==='string'&&value.startsWith('data:image/svg+xml;base64,')?value:'';
}
function linuxModes(){return modes.filter(m=>!['lectures','coding'].includes(m.id)).map(m=>({...m,label:({code:'Commands',uml:'Diagrams',book:'Book',scenarios:'Cases'})[m.id]||m.label})).concat({id:'linuxlabs',label:'Linux labs',icon:'edit',color:'bg-mint text-mint-ink'});}
function linuxModeCount(id,t,c){return ({slides:'Interactive chapter lecture',outline:`${c.chapters.length} chapter maps`,code:`${c.linuxBook.originalCodeBlocks} original examples`,uml:'Fit-to-pane operational diagrams',book:'Complete original EPUB',linuxlabs:'33 local Bash fixture labs',flashcards:`${t.cards} cards`,scenarios:`${t.scenarios} cases`})[id]||'';}
function linuxBlocks(t){return (t.blocks||[]).map(b=>b.type==='code'?`<section class="linux-command"><span class="teaching-kicker">ORIGINAL COMMAND / CONFIGURATION / TRACE</span><pre><code>${escape(b.code)}</code></pre><p class="teaching-caption">${escape(t.sourceRef)} · Read the surrounding preconditions before use.</p><button class="btn" data-action="linux-source-download" data-block="${escape(b.id)}">Download exact source text</button></section>`:`<p class="reader-paragraph linux-prose">${escape(b.text)}</p>`).join('');}
function linuxFigure(m){return `<figure class="linux-figure"><img class="linux-diagram" src="${escape(linuxImage(m.image))}" alt="${escape(m.title+'. '+m.contract)}"><figcaption>${escape(m.contract)}<br>Arrows show an inspection sequence, not a kernel data flow.</figcaption><button class="btn" data-action="linux-diagram-open">Open diagram full screen</button></figure>`;}
function linuxLab(lab){if(!lab)return '<p>This reference chapter has no executable fixture lab. Use its original procedures and worksheets.</p>';const draft=progress().linuxDrafts?.[String(topic().chapter)]??lab.starter;return `<section class="linux-lab"><h3>${escape(lab.title)}</h3><p>${escape(lab.scope)}</p><p>Run with Bash on GNU/Linux without sudo. The solution creates and removes its own temporary directory. Fixture results demonstrate the stated contract; they do not configure a production service.</p><label for="linux-lab-editor">Your solution · saved in this browser</label><textarea id="linux-lab-editor" spellcheck="false" wrap="off" maxlength="60000">${escape(draft)}</textarea><div class="linux-tools"><button class="btn" data-action="linux-lab-download">Download my .sh</button><button class="btn" data-action="linux-lab-reset">Reset starter</button></div><pre><code>bash -n linux-lab.sh &amp;&amp; bash linux-lab.sh</code></pre><details class="answer-reveal"><summary>Compare the verified solution and expected output</summary><pre><code>${escape(lab.code)}</code></pre><strong>Expected stdout · exit 0 · empty stderr</strong><pre>${escape(lab.output)}</pre><p>The installer does not execute the book’s original privileged commands. These local fixture solutions are checked by the added test suite.</p><button class="btn" data-action="linux-lab-solution">Download verified solution .sh</button></details></section>`;}
function linuxWorked(g){return (g.workedTopicIds||[]).map(id=>course().topics.find(t=>t.id===id)).filter(Boolean).map(t=>`<section><h3>${escape(t.title)}</h3>${linuxBlocks(t)}</section>`).join('');}
function linuxBookView(){return `<article class="panel teaching-reader"><h2 class="lesson-heading">Linux System Administration</h2><p>The complete supplied EPUB: 33 main chapters, introductory material, four appendices and primary references. All 490 numbered section examples and 735 original command, configuration and trace blocks are retained.</p><button class="btn btn-primary" data-action="linux-epub">Download original EPUB</button><button class="btn" data-action="coverage">Browse all chapters</button><p>Read inside Study Studio with Outline, open the chapter’s interactive Slides, or use Commands for every original example in the selected chapter.</p></article>`;}
function linuxWorkspace(t){
  const g=chapterGuide(t.chapter);if(!g)return '<p>Choose a chapter.</p>';
  if(state.mode==='book')return linuxBookView();
  if(state.mode==='linuxlabs')return `<article class="panel teaching-reader"><h2 class="lesson-heading">${escape(g.title)} · local lab</h2>${linuxLab(g.labs?.[0])}</article>`;
  if(state.mode==='uml')return `<article class="panel teaching-reader"><h2 class="lesson-heading">${escape(g.model.title)}</h2>${linuxFigure(g.model)}<h3>What can go wrong?</h3><p>${escape(g.model.failure)}</p><details class="answer-reveal"><summary>Explain the operational contract</summary><p>${escape(g.model.contract)}</p></details></article>`;
  if(state.mode==='code')return `<article class="panel teaching-reader"><h2 class="lesson-heading">${escape(g.title)} · original examples</h2><p>These are exact examples from the book, including configuration and illustrative traces. They are displayed as text and are not submitted to the C++ compiler. Use the full section instructions for requirements and verification.</p>${course().topics.filter(x=>x.chapter===t.chapter&&x.blocks?.some(b=>b.type==='code')).map(x=>`<section><h3>${escape(x.title)}</h3><button class="source-link" data-action="read-topic" data-id="${escape(x.id)}">Open full source context</button>${(x.blocks||[]).filter(b=>b.type==='code').map(b=>`<pre class="linux-code"><code>${escape(b.code)}</code></pre>`).join('')}</section>`).join('')}</article>`;
  const map=state.lessonView==='map'||(state.lessonView!=='lesson'&&t.id===g.startTopicId);
  return `<article class="panel teaching-reader linux-reader">${guideTrail(t,g)}<div class="linux-heading"><h2 class="lesson-heading">${escape(map?g.title:t.title)}</h2>${bookmarkButton(t)}</div>${map?`<div class="linux-discussion-grid"><div><h3>${escape(g.model.title)}</h3><p>${escape(g.workshop.problem)}</p><p>${escape(g.model.contract)}</p><ul>${g.objectives.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><div class="linux-tools"><button class="btn btn-primary" data-action="read-topic" data-id="${escape(g.firstLessonId)}">Read first lesson</button><button class="btn" data-action="mode" data-mode="slides">Open chapter slides</button><button class="btn" data-action="mode" data-mode="linuxlabs">Open local lab</button></div></div><aside>${linuxFigure(g.model)}</aside></div><details class="answer-reveal"><summary>Chapter sections · ${g.sections.length} reading entries</summary>${chapterMapCards(g)}</details><section id="chapter-workshop"><h3>Original worked example and chapter discussion</h3>${linuxWorked(g)||linuxBlocks(t)}</section>${linuxLab(g.labs?.[0])}`:`<div class="linux-discussion-grid"><section>${linuxBlocks(t)}</section><aside>${linuxFigure(g.model)}<details class="answer-reveal"><summary>Discuss the evidence</summary><p>${escape(g.model.contract)}</p><p>${escape(g.model.failure)}</p></details><button class="btn" data-action="chapter-map">Chapter discussion and worked example</button></aside></div>`}${teachingNotes(t)}${readingFooter(t)}</article>`;
}
function linuxSlidesWorkbench(s){
  if(s.linuxModel)return linuxFigure(s.linuxModel)+`<p>${escape(s.linuxModel.failure)}</p>`;
  if(s.linuxCommand)return `<span class="slides-eyebrow">EXACT LINUX SOURCE EXAMPLE</span><pre class="linux-code"><code>${escape(s.linuxCommand.text)}</code></pre><p>${escape(s.linuxCommand.interpretation)}</p><p class="slides-network">${escape(s.linuxCommand.source)}. Run only with the book’s stated lab preconditions. This page does not run a host shell.</p><button class="slides-btn" data-action="linux-slide-copy">Copy source text</button>`;
  if(s.linuxLab)return linuxLab(s.linuxLab);
  return `<section class="slides-reading"><span class="slides-eyebrow">ORIGINAL CHAPTER DISCUSSION</span>${(s.linuxReading||[]).map(p=>`<p class="linux-prose">${escape(p)}</p>`).join('')}</section>`;
}
function linuxCurrentLab(){return state.mode==='slides'?slidesCurrent()?.linuxLab:chapterGuide()?.labs?.[0];}
function linuxZoom(value){const viewer=document.querySelector('.linux-zoom-view');if(!viewer)return;const zoom=Math.max(1,Math.min(4,value));viewer.dataset.zoom=String(zoom);viewer.style.setProperty('--linux-zoom',zoom);const status=document.querySelector('#linux-zoom-status');if(status)status.textContent=Math.round(zoom*100)+'%';}
document.addEventListener('input',e=>{if(!linuxCourse()||e.target.id!=='linux-lab-editor')return;const p=progress();p.linuxDrafts??={};p.linuxDrafts[String(topic().chapter)]=e.target.value;remember();});
document.addEventListener('click',async e=>{
  const el=e.target.closest('[data-action^="linux-"]');if(!el||!linuxCourse())return;
  const lab=linuxCurrentLab();
  switch(el.dataset.action){
    case 'linux-source-download':{const b=course().topics.flatMap(t=>t.blocks||[]).find(b=>b.id===el.dataset.block&&b.type==='code');if(b)slidesDownload(b.id+'.txt',b.code);break;}
    case 'linux-lab-download':if(lab)slidesDownload('linux-lab.sh',progress().linuxDrafts?.[String(topic().chapter)]??lab.starter);break;
    case 'linux-lab-solution':if(lab)slidesDownload('linux-lab.sh',lab.code);break;
    case 'linux-lab-reset':if(lab){progress().linuxDrafts??={};delete progress().linuxDrafts[String(topic().chapter)];remember();if(state.mode==='slides')renderSlidesWorkspace();else renderWorkspace();}break;
    case 'linux-slide-copy':if(slidesCurrent()?.linuxCommand)slidesCopy(slidesCurrent().linuxCommand.text);break;
    case 'linux-epub':{const book=course().linuxBook.epub;const a=document.createElement('a');const value=typeof book==='string'?book:book?.$asset;if(!value||!(value.startsWith('data:application/epub+zip;base64,')||value==='assets/linux-admin/Linux_System_Administration.epub'))break;a.href=value;a.download='Linux_System_Administration.epub';a.click();break;}
    case 'linux-diagram-open':{const m=state.mode==='slides'&&slidesCurrent()?.linuxModel?slidesCurrent().linuxModel:chapterGuide()?.model;if(!m)break;modal(m.title,`<div class="linux-tools"><button class="btn" data-action="linux-fit">Fit screen</button><button class="btn" data-action="linux-zoom-out" aria-label="Zoom out">−</button><span id="linux-zoom-status" aria-live="polite">100%</span><button class="btn" data-action="linux-zoom-in" aria-label="Zoom in">+</button></div><div class="linux-zoom-view" data-zoom="1"><div class="linux-zoom-sheet"><img src="${escape(linuxImage(m.image))}" alt="${escape(m.title+'. '+m.contract)}"></div></div>`);DIALOG.classList.add('linux-diagram-dialog');break;}
    case 'linux-fit':linuxZoom(1);break;
    case 'linux-zoom-in':linuxZoom(Number(document.querySelector('.linux-zoom-view')?.dataset.zoom||1)+.25);break;
    case 'linux-zoom-out':linuxZoom(Number(document.querySelector('.linux-zoom-view')?.dataset.zoom||1)-.25);break;
  }
});
DIALOG.addEventListener('close',()=>DIALOG.classList.remove('linux-diagram-dialog'));
DIALOG.addEventListener('wheel',e=>{const viewer=e.target.closest('.linux-zoom-view');if(!viewer||!linuxCourse())return;e.preventDefault();linuxZoom(Number(viewer.dataset.zoom)+(e.deltaY<0?.15:-.15));},{passive:false});
